/* =========================================================
   DER LERNWEG — ein Kurs mit Anfang, Reihenfolge und Ziel
   ---------------------------------------------------------
   GEWÜNSCHT: „Es müsste auch einen richtigen Kurs geben, wo
   man anfängt und geführt wird — Begrüßung, Verabschiedung,
   persönliche Vorstellung … dass sich das aufbaut wie in
   Lehrbüchern, die Module der Reihe nach, für A1 bis C2, im
   Deutschen und im Italienischen."

   Was hier NICHT steht: neue Inhalte. Jedes Modul verweist auf
   Dinge, die es auf der Seite schon gibt — eine Bilderwelt-Szene,
   eine Übungskategorie, ein Grammatikthema, ein Spiel. Der
   Lernweg ist die REIHENFOLGE, nicht der Stoff. Genau das hat
   bisher gefehlt: Alles war da, aber niemand sagte einem, wo man
   anfängt und was als Nächstes kommt.

   Aufbau eines Moduls:
     id      — eindeutig, wird im Fortschritt gespeichert
     titel   — was man lernt, in Alltagssprache
     icon    — ein Zeichen für die Wegkarte
     text    — ein Satz: warum dieses Modul jetzt kommt
     schritte— die Stationen, der Reihe nach:
                 { art: "szene",    ziel: "<Szenen-Kennung>" }
                 { art: "uebung",   ziel: "<Kategorie-Kennung>" }
                 { art: "grammatik",ziel: "<Stufe>" }
                 { art: "spiel",    ziel: "<sub-Kennung>" }
   Ein Schritt gilt als geschafft, wenn man ihn einmal mit
   mindestens 70 Prozent abgeschlossen hat.
   ========================================================= */
window.DMA_LERNWEG = {
  de: {
    A1: [
      { id: "de-a1-1", titel: "Hallo und tschüss", icon: "👋",
        text: "Der erste Satz, den man in einer Sprache braucht, ist ein Gruß. Hier lernst du, welcher Gruß wann passt — und wann man duzt.",
        schritte: [{ art: "uebung", ziel: "begruessung" }] },
      { id: "de-a1-2", titel: "Ich stelle mich vor", icon: "🙋",
        text: "Name, Herkunft, Sprachen: die Sätze, mit denen jedes Gespräch anfängt.",
        schritte: [{ art: "uebung", ziel: "begruessung" }, { art: "grammatik", ziel: "A1" }] },
      { id: "de-a1-3", titel: "Zahlen von null bis hundert", icon: "🔢",
        text: "Ohne Zahlen geht nichts: Preise, Uhrzeiten, Hausnummern, das Alter. Und die deutsche Eigenheit, den Einer vorn zu sagen.",
        schritte: [{ art: "uebung", ziel: "zahlen" }] },
      { id: "de-a1-4", titel: "Wie spät ist es?", icon: "🕐",
        text: "„Halb acht“ ist 7:30 — im Deutschen zählt man auf die kommende Stunde zu. Das ist die häufigste Verwechslung überhaupt.",
        schritte: [{ art: "uebung", ziel: "uhrzeit" }] },
      { id: "de-a1-5", titel: "Tage, Monate, Jahreszeiten", icon: "📅",
        text: "Am Montag, im Mai, um acht: drei Präpositionen, die man sich zusammen merkt.",
        schritte: [{ art: "uebung", ziel: "wochentage" }, { art: "uebung", ziel: "monate" }] },
      { id: "de-a1-6", titel: "Meine Familie", icon: "👨‍👩‍👧",
        text: "Wer ist der Schwager, wer die Nichte? Und die Possessivpronomen, die dazugehören.",
        schritte: [{ art: "uebung", ziel: "familie" }] },
      { id: "de-a1-7", titel: "Bei mir zu Hause", icon: "🏠",
        text: "Geh durch die Zimmer und tippe alles an, was darin steht. Jedes Ding sagt dir seinen Artikel.",
        schritte: [{ art: "szene", ziel: "kinderzimmer" }, { art: "szene", ziel: "wohnzimmer" },
                   { art: "uebung", ziel: "moebel" }] },
      { id: "de-a1-8", titel: "Essen und Trinken", icon: "🍽️",
        text: "Obst, Gemüse, Getränke, Gerichte — und wie man sie benennt.",
        schritte: [{ art: "szene", ziel: "kueche" }, { art: "uebung", ziel: "essen" }] },
      { id: "de-a1-9", titel: "Mein Körper", icon: "🧍",
        text: "Vom Kopf bis zum Zeh. Beim Arzt braucht man diese Wörter sofort.",
        schritte: [{ art: "szene", ziel: "koerper" }, { art: "uebung", ziel: "koerper" }] },
      { id: "de-a1-10", titel: "Mein Tag", icon: "🗓️",
        text: "Aufstehen, duschen, frühstücken, arbeiten, schlafen gehen — und die trennbaren Verben dazu.",
        schritte: [{ art: "szene", ziel: "tagesablauf" }, { art: "uebung", ziel: "alltagsverben" }] },
      { id: "de-a1-11", titel: "Der, die oder das?", icon: "🏷️",
        text: "Der Artikel gehört zum Wort wie die Farbe zum Ding. Am besten beides zusammen lernen.",
        schritte: [{ art: "uebung", ziel: "artikel" }, { art: "spiel", ziel: "sub-artikelgarten" }] },
      { id: "de-a1-12", titel: "Einer oder mehrere?", icon: "👥",
        text: "Der Plural hat im Deutschen keine einzige Regel, sondern fünf Muster. Übung hilft mehr als Auswendiglernen.",
        schritte: [{ art: "uebung", ziel: "plural" }] },
    ],
    A2: [
      { id: "de-a2-1", titel: "Einkaufen gehen", icon: "🛒",
        text: "Fragen, was etwas kostet. Nach der Größe fragen. Umtauschen. Die Sätze, die man im Laden wirklich sagt.",
        schritte: [{ art: "szene", ziel: "supermarkt" }, { art: "uebung", ziel: "einkaufen" }] },
      { id: "de-a2-2", titel: "Was ziehe ich an?", icon: "👕",
        text: "Kleidung mit Artikel — und die Sätze für die Umkleidekabine.",
        schritte: [{ art: "szene", ziel: "kleidung" }, { art: "uebung", ziel: "kleidung" }] },
      { id: "de-a2-3", titel: "Wo ist was?", icon: "🧷",
        text: "In, an, auf, über, unter: die Wechselpräpositionen und die Frage „wohin?“ gegen „wo?“.",
        schritte: [{ art: "uebung", ziel: "praepositionen" }, { art: "spiel", ziel: "sub-katzenzimmer" }] },
      { id: "de-a2-4", titel: "Wie ist das Wetter?", icon: "🌦️",
        text: "Wetter beschreiben und Dinge beschreiben: Form, Farbe, Material, Größe.",
        schritte: [{ art: "szene", ziel: "wetter" }, { art: "uebung", ziel: "beschreiben" }] },
      { id: "de-a2-5", titel: "Unterwegs", icon: "🚆",
        text: "Straße, Bahnhof, Fahrkarte, Umsteigen — die Wörter fürs Ankommen und Weiterkommen.",
        schritte: [{ art: "szene", ziel: "strasse" }, { art: "szene", ziel: "bahnhof" }] },
      { id: "de-a2-6", titel: "Beim Arzt", icon: "🩺",
        text: "Beschwerden schildern, Termine machen, den Beipackzettel verstehen.",
        schritte: [{ art: "szene", ziel: "arztpraxis" }, { art: "spiel", ziel: "sub-arzt" }] },
      { id: "de-a2-7", titel: "Von gestern erzählen", icon: "🕰️",
        text: "Das Perfekt: mit „haben“ oder mit „sein“? Und wo das Partizip im Satz steht.",
        schritte: [{ art: "uebung", ziel: "tagesablauf" }, { art: "uebung", ziel: "zeitformen" }] },
      { id: "de-a2-8", titel: "Im Haushalt", icon: "🧹",
        text: "Putzen, waschen, aufräumen, kochen — die Dinge und die Tätigkeiten.",
        schritte: [{ art: "szene", ziel: "badezimmer" }, { art: "uebung", ziel: "haushalt" }] },
      { id: "de-a2-9", titel: "Freizeit und Sport", icon: "⚽",
        text: "Hobbys, Vereine, Ausflüge — und die Verben, die man dafür braucht.",
        schritte: [{ art: "uebung", ziel: "freizeit" }] },
      { id: "de-a2-10", titel: "Tiere", icon: "🐾",
        text: "Haustiere, Bauernhof, Wald und Zoo.",
        schritte: [{ art: "szene", ziel: "bauernhof" }, { art: "uebung", ziel: "tiere" }] },
      { id: "de-a2-11", titel: "Fragen stellen", icon: "❓",
        text: "W-Fragen und Ja/Nein-Fragen — und warum das Verb dabei vorn steht.",
        schritte: [{ art: "uebung", ziel: "fragen" }, { art: "uebung", ziel: "wortstellung" }] },
      { id: "de-a2-12", titel: "Nein sagen", icon: "🚫",
        text: "„nicht“ oder „kein“? Eine kleine Frage mit einer klaren Regel.",
        schritte: [{ art: "uebung", ziel: "verneinung" }] },
    ],
    B1: [
      { id: "de-b1-1", titel: "Sätze verbinden", icon: "🔗",
        text: "weil, obwohl, damit, bevor: Nebensätze schieben das Verb ans Ende — das ist der größte Sprung nach A2.",
        schritte: [{ art: "uebung", ziel: "nebensatz" }] },
      { id: "de-b1-2", titel: "Die vier Fälle", icon: "🧮",
        text: "Nominativ, Genitiv, Dativ, Akkusativ — und woran man erkennt, welcher gemeint ist.",
        schritte: [{ art: "uebung", ziel: "faelle" }] },
      { id: "de-b1-3", titel: "Gefühle benennen", icon: "💛",
        text: "Statt „gut“ und „schlecht“: Freude, Ärger, Stolz, Sorge, Erleichterung.",
        schritte: [{ art: "uebung", ziel: "gefuehle" }] },
      { id: "de-b1-4", titel: "Freundschaft", icon: "🤝",
        text: "Einladen, absagen, sich entschuldigen — und die Wendungen für Nähe und Vertrauen.",
        schritte: [{ art: "uebung", ziel: "freundschaft" }] },
      { id: "de-b1-5", titel: "Was man wirklich sagt", icon: "💬",
        text: "Umgangssprache: keinen Bock, alles klar, Hals- und Beinbruch — und wo diese Wendungen nicht hingehören.",
        schritte: [{ art: "uebung", ziel: "umgangssprache" }] },
      { id: "de-b1-6", titel: "Redewendungen", icon: "🗣️",
        text: "Bilder, die man nicht wörtlich nehmen darf — und die trotzdem jeder benutzt.",
        schritte: [{ art: "uebung", ziel: "redewendungen" }] },
      { id: "de-b1-7", titel: "Werkzeug und Material", icon: "🔧",
        text: "Werkstatt, Baustelle, Heimwerken — ein Wortfeld, das im Alltag oft fehlt.",
        schritte: [{ art: "szene", ziel: "werkstatt" }, { art: "uebung", ziel: "werkzeug" }] },
      { id: "de-b1-8", titel: "Relativsätze", icon: "🧵",
        text: "„Der Mann, der …“ — ein Satz im Satz, der beschreibt, wen oder was man meint.",
        schritte: [{ art: "uebung", ziel: "relativsatz" }] },
      { id: "de-b1-9", titel: "Verben mit Rückbezug", icon: "🔄",
        text: "sich freuen, sich ärgern, sich erinnern: Verben, die ein „sich“ brauchen.",
        schritte: [{ art: "uebung", ziel: "reflexiv" }] },
      { id: "de-b1-10", titel: "Musik", icon: "🎵",
        text: "Instrumente, Stimmen, Lieder — und was das Deutsche aus der Musik an Bildern nimmt.",
        schritte: [{ art: "uebung", ziel: "musik" }] },
      { id: "de-b1-11", titel: "Verwechselbare Wörter", icon: "🔀",
        text: "kennen oder wissen? als oder wie? das oder dass? Kleine Paare mit klaren Regeln.",
        schritte: [{ art: "uebung", ziel: "kennen-wissen" }, { art: "uebung", ziel: "als-wie" },
                   { art: "uebung", ziel: "das-dass" }] },
      { id: "de-b1-12", titel: "Zu-Sätze", icon: "➡️",
        text: "„Ich habe vor, morgen zu kommen“ — Infinitivsätze mit zu.",
        schritte: [{ art: "uebung", ziel: "infinitivsatz" }] },
    ],
    B2: [
      { id: "de-b2-1", titel: "Das Passiv", icon: "🔁",
        text: "Wenn die Handlung wichtiger ist als die handelnde Person: „Das Haus wird gebaut.“",
        schritte: [{ art: "uebung", ziel: "passiv" }] },
      { id: "de-b2-2", titel: "Der Konjunktiv", icon: "💭",
        text: "Wünsche, Höflichkeit, indirekte Rede — drei sehr verschiedene Aufgaben für eine Form.",
        schritte: [{ art: "uebung", ziel: "konjunktiv" }] },
      { id: "de-b2-3", titel: "Je … desto", icon: "📈",
        text: "Zwei Dinge, die sich zusammen verändern — und die Wortstellung, die dazugehört.",
        schritte: [{ art: "uebung", ziel: "jedesto" }] },
      { id: "de-b2-4", titel: "Zweiteilige Verbindungen", icon: "🪢",
        text: "entweder … oder, zwar … aber, weder … noch: Konnektoren, die den Satz gliedern.",
        schritte: [{ art: "uebung", ziel: "konnektoren" }] },
      { id: "de-b2-5", titel: "Funktionsverbgefüge", icon: "⚙️",
        text: "„zur Verfügung stellen“, „in Betracht ziehen“ — die Sprache von Ämtern und Berichten.",
        schritte: [{ art: "uebung", ziel: "funktionsverben" }] },
      { id: "de-b2-6", titel: "Häufige Fehler", icon: "🎯",
        text: "Die Stellen, an denen auch Fortgeschrittene noch stolpern.",
        schritte: [{ art: "uebung", ziel: "haeufige-fehler" }] },
      { id: "de-b2-7", titel: "ß oder ss", icon: "✒️",
        text: "Eine Regel, die sich an der Länge des Vokals davor entscheidet.",
        schritte: [{ art: "uebung", ziel: "ss-eszett" }] },
      { id: "de-b2-8", titel: "Wörter, die gleich klingen", icon: "🔊",
        text: "Seite und Saite, Lehre und Leere: Homophone und wie man sie auseinanderhält.",
        schritte: [{ art: "uebung", ziel: "homophone" }] },
      { id: "de-b2-9", titel: "Vorsilben", icon: "🧩",
        text: "auf-, ab-, über-, ver-: Wie eine Vorsilbe die Bedeutung eines Verbs verschiebt.",
        schritte: [{ art: "uebung", ziel: "praefixverben" }] },
      { id: "de-b2-10", titel: "Sinn erfassen", icon: "🧠",
        text: "Nicht mehr Regel, sondern Bedeutung: Was will der Satz sagen?",
        schritte: [{ art: "uebung", ziel: "sinn-trainer" }] },
    ],
    C1: [
      { id: "de-c1-1", titel: "Partizipien als Beschreibung", icon: "📎",
        text: "„Die vom Sturm beschädigten Dächer“ — ein ganzer Nebensatz, zusammengefaltet.",
        schritte: [{ art: "uebung", ziel: "partizip" }] },
      { id: "de-c1-2", titel: "Modalpartikeln", icon: "🎚️",
        text: "doch, mal, eben, halt: winzige Wörter, die den Ton eines Satzes komplett drehen.",
        schritte: [{ art: "uebung", ziel: "modalpartikeln" }] },
      { id: "de-c1-3", titel: "Wortbildung", icon: "🏗️",
        text: "Wie das Deutsche neue Wörter baut — und wie man ein unbekanntes Wort trotzdem versteht.",
        schritte: [{ art: "uebung", ziel: "wortbildung" }] },
      { id: "de-c1-4", titel: "Doppelt gemoppelt", icon: "🔁",
        text: "„weißer Schimmel“, „bereits schon“: überflüssige Wiederholungen erkennen.",
        schritte: [{ art: "uebung", ziel: "doppelt-gemoppelt" }] },
      { id: "de-c1-5", titel: "Genaue Wortwahl", icon: "🎯",
        text: "Synonyme sind selten wirklich gleich. Hier zählt der Unterschied.",
        schritte: [{ art: "uebung", ziel: "synonyme" }, { art: "uebung", ziel: "wortpaare" }] },
      { id: "de-c1-6", titel: "Stil", icon: "🖋️",
        text: "Dasselbe sagen — nur besser. Register, Rhythmus, Genauigkeit.",
        schritte: [{ art: "uebung", ziel: "stil" }] },
    ],
    C2: [
      { id: "de-c2-1", titel: "Der ganze Wortschatz", icon: "📚",
        text: "Quer durch alle Themen, auf höchster Stufe.",
        schritte: [{ art: "uebung", ziel: "wortschatz" }] },
      { id: "de-c2-2", titel: "Feinheiten der Grammatik", icon: "🔬",
        text: "Zeitformen, Fälle, Konjunktiv — alles noch einmal, auf der Stufe, auf der es schwierig wird.",
        schritte: [{ art: "uebung", ziel: "zeitformen" }, { art: "uebung", ziel: "konjunktiv" }] },
      { id: "de-c2-3", titel: "Deutschland kennen", icon: "🏆",
        text: "Landeskunde: Geschichte, Politik, Alltag, Regionen.",
        schritte: [{ art: "uebung", ziel: "quiz" }] },
      { id: "de-c2-4", titel: "Betonung sicher hören", icon: "🔉",
        text: "Wo liegt der Ton, und ist der Vokal lang oder kurz? Die letzte Feinheit der Aussprache.",
        schritte: [{ art: "spiel", ziel: "sub-stresstrainer" }] },
      { id: "de-c2-5", titel: "Alles zusammen", icon: "🎓",
        text: "Lückentexte quer durch die Sprache — der Abschluss des Wegs.",
        schritte: [{ art: "uebung", ziel: "lueckentext" }] },
    ],
  },
  it: {
    A1: [
      { id: "it-a1-1", titel: "Come si pronuncia?", icon: "🔊",
        text: "Zuerst das Lesen: c und g vor hellen und dunklen Vokalen, gn, gli, sc, das stumme h. Wer das kann, liest jedes italienische Wort richtig.",
        schritte: [{ art: "uebung", ziel: "it-aussprache" }] },
      { id: "it-a1-2", titel: "Ciao! Buongiorno!", icon: "👋",
        text: "Grüßen, sich vorstellen, sich verabschieden — und wann ciao passt und wann nicht.",
        schritte: [{ art: "uebung", ziel: "it-begruessung" }] },
      { id: "it-a1-3", titel: "il, lo, la", icon: "🏷️",
        text: "Der Artikel richtet sich nicht nur nach dem Geschlecht, sondern nach dem ersten LAUT des Wortes. Das ist die wichtigste Regel des Anfangs.",
        schritte: [{ art: "uebung", ziel: "it-artikelregeln" }, { art: "uebung", ziel: "it-artikel" }] },
      { id: "it-a1-4", titel: "I numeri", icon: "🔢",
        text: "Zählen auf Italienisch — und der Unterschied zum Deutschen: hier wird von vorn gelesen.",
        schritte: [{ art: "uebung", ziel: "it-zahlen" }] },
      { id: "it-a1-5", titel: "Che ore sono?", icon: "🕐",
        text: "Die Uhrzeit im Plural, „le tre e mezza“ für halb vier — und warum das anders gezählt wird als im Deutschen.",
        schritte: [{ art: "uebung", ziel: "it-uhrzeit" }] },
      { id: "it-a1-6", titel: "Giorni e mesi", icon: "📅",
        text: "Wochentage und Monate, alle klein geschrieben — und das Datum mit der Grundzahl.",
        schritte: [{ art: "uebung", ziel: "it-wochentage" }, { art: "uebung", ziel: "it-monate" }] },
      { id: "it-a1-7", titel: "La casa", icon: "🏠",
        text: "Durch die Zimmer gehen und alles antippen: jedes Ding sagt dir seinen Artikel und seine Betonung.",
        schritte: [{ art: "szene", ziel: "kinderzimmer" }, { art: "szene", ziel: "wohnzimmer" },
                   { art: "uebung", ziel: "it-wohnen" }] },
      { id: "it-a1-8", titel: "Il corpo", icon: "🧍",
        text: "Die Körperteile — die Wörter, die man beim Arzt sofort braucht.",
        schritte: [{ art: "szene", ziel: "koerper" }, { art: "uebung", ziel: "it-koerper" }] },
      { id: "it-a1-9", titel: "La giornata", icon: "🗓️",
        text: "Aufstehen, sich waschen, frühstücken: die reflexiven Verben des Tages.",
        schritte: [{ art: "szene", ziel: "tagesablauf" }, { art: "uebung", ziel: "it-tagesablauf" }] },
      { id: "it-a1-10", titel: "Il plurale", icon: "👥",
        text: "-o wird zu -i, -a zu -e. Kein angehängtes -s wie im Englischen.",
        schritte: [{ art: "uebung", ziel: "it-plural" }] },
    ],
    A2: [
      { id: "it-a2-1", titel: "Fare la spesa", icon: "🛒",
        text: "Quanto costa? Vorrei… — die Sätze für Markt, Laden und Kasse.",
        schritte: [{ art: "szene", ziel: "supermarkt" }, { art: "uebung", ziel: "it-einkaufen" }] },
      { id: "it-a2-2", titel: "A tavola", icon: "🍽️",
        text: "Bestellen, essen, bezahlen — und die Wörter für alles, was auf dem Tisch steht.",
        schritte: [{ art: "szene", ziel: "restaurant" }, { art: "uebung", ziel: "it-essen" }] },
      { id: "it-a2-3", titel: "I verbi", icon: "⏳",
        text: "Die Endung sagt schon, wer handelt — deshalb steht das Pronomen meist gar nicht da.",
        schritte: [{ art: "uebung", ziel: "it-verben" }] },
      { id: "it-a2-4", titel: "Gli aggettivi", icon: "🎨",
        text: "Das Adjektiv richtet sich nach dem Nomen — und steht fast immer dahinter.",
        schritte: [{ art: "uebung", ziel: "it-adjektive" }, { art: "uebung", ziel: "it-beschreiben" }] },
      { id: "it-a2-5", titel: "Che tempo fa?", icon: "🌦️",
        text: "Beim Wetter steht „fare“ — und „fa caldo“ heißt etwas anderes als „ho caldo“.",
        schritte: [{ art: "szene", ziel: "wetter" }, { art: "uebung", ziel: "it-wetter" }] },
      { id: "it-a2-6", titel: "Le preposizioni", icon: "🧷",
        text: "a + il wird zu al, di + la zu della. Diese Verschmelzung ist Pflicht.",
        schritte: [{ art: "uebung", ziel: "it-praepositionen" }, { art: "spiel", ziel: "sub-katzenzimmer" }] },
      { id: "it-a2-7", titel: "I vestiti", icon: "👕",
        text: "Kleidung mit Artikel, vom T-Shirt bis zum Mantel.",
        schritte: [{ art: "szene", ziel: "kleidung" }, { art: "uebung", ziel: "it-kleidung" }] },
      { id: "it-a2-8", titel: "In viaggio", icon: "🚆",
        text: "Straße, Bahnhof, Fahrkarte — unterwegs in Italien.",
        schritte: [{ art: "szene", ziel: "bahnhof" }, { art: "uebung", ziel: "it-unterwegs" }] },
    ],
    B1: [
      { id: "it-b1-1", titel: "Il passato", icon: "🕰️",
        text: "Das passato prossimo mit essere oder avere — und wann sich das Partizip anpasst.",
        schritte: [{ art: "uebung", ziel: "it-vergangenheit" }] },
      { id: "it-b1-2", titel: "Modi di dire", icon: "💬",
        text: "Feste Wendungen, die man nicht wörtlich übersetzen kann.",
        schritte: [{ art: "uebung", ziel: "it-alltag" }] },
      { id: "it-b1-3", titel: "Gli animali e la natura", icon: "🐾",
        text: "Tiere, Garten, Pflanzen — das Wortfeld draußen.",
        schritte: [{ art: "szene", ziel: "bauernhof" }, { art: "uebung", ziel: "it-tiere" },
                   { art: "uebung", ziel: "it-natur" }] },
      { id: "it-b1-4", titel: "A scuola e al lavoro", icon: "🏫",
        text: "Klassenzimmer, Werkstatt, Werkzeug — die Wörter fürs Lernen und Arbeiten.",
        schritte: [{ art: "szene", ziel: "klassenzimmer" }, { art: "uebung", ziel: "it-schule" },
                   { art: "uebung", ziel: "it-werkzeug" }] },
      { id: "it-b1-5", titel: "In cucina e in bagno", icon: "🧹",
        text: "Haushalt, Geräte, Geschirr.",
        schritte: [{ art: "szene", ziel: "badezimmer" }, { art: "uebung", ziel: "it-haushalt" }] },
    ],
    B2: [
      { id: "it-b2-1", titel: "Vocabolario avanzato", icon: "🧠",
        text: "Wortschatz nach Lebensbereichen, auf höherer Stufe.",
        schritte: [{ art: "uebung", ziel: "it-wortschatz" }] },
      { id: "it-b2-2", titel: "Grammatica in profondità", icon: "🔬",
        text: "Verben, Artikel, Präpositionen — noch einmal, dort wo es schwierig wird.",
        schritte: [{ art: "uebung", ziel: "it-verben" }, { art: "uebung", ziel: "it-praepositionen" }] },
    ],
    C1: [
      { id: "it-c1-1", titel: "Sfumature", icon: "🎚️",
        text: "Feinheiten: Wortwahl, Ton, Register.",
        schritte: [{ art: "uebung", ziel: "it-alltag" }, { art: "uebung", ziel: "it-wortschatz" }] },
      { id: "it-c1-2", titel: "L'accento giusto", icon: "🔉",
        text: "Die Betonung sicher treffen — auch bei den Wörtern, die man ihr nicht ansieht.",
        schritte: [{ art: "uebung", ziel: "it-aussprache" }, { art: "spiel", ziel: "sub-stresstrainer" }] },
    ],
    C2: [
      { id: "it-c2-1", titel: "Tutto insieme", icon: "🎓",
        text: "Alles zusammen — quer durch Grammatik und Wortschatz.",
        schritte: [{ art: "uebung", ziel: "it-wortschatz" }, { art: "uebung", ziel: "it-verben" },
                   { art: "uebung", ziel: "it-adjektive" }] },
    ],
  },
};
