/* =========================================================
   FESTE, FEIERTAGE UND KULTUR
   ---------------------------------------------------------
   GEWÜNSCHT: „Zu Festen und Feiertagen möchte ich auch noch
   irgendwas haben — ja, Weihnachten, Ostern und die wichtigsten
   Sachen zur deutschen Kultur."

   Zwei Teile:

   FESTE — der Jahreslauf. Zu jedem Fest: wann es ist, ob die
   Läden zuhaben, was man tut, was man sagt, und die Wörter, die
   man dafür braucht.

   ALLTAG — das Ungeschriebene. Pünktlichkeit, Ruhezeiten,
   Mülltrennung, Pfand, Termine. Nichts davon steht in einem
   Gesetz, das man liest, und alles davon merkt man, wenn man es
   falsch macht. Genau das gehört zur Integration.

   „gesetzlich" heißt: arbeitsfrei, Läden zu, Busse fahren wie
   sonntags. „Brauch" heißt: normaler Arbeitstag, aber alle
   machen mit.
   ========================================================= */
window.DMA_FESTE = (() => {

  const F = (id, name, syl, wann, art, monat, worum, ablauf, woerter, saetze, hinweis) =>
    ({ id, name, syl, wann, art, monat, worum, ablauf, woerter, saetze, hinweis });
  const w = (wort, syl, was) => ({ wort, syl, was });

  const FESTE_DE = [
    F("neujahr", "Neujahr", "NEU-jahr", "1. Januar", "gesetzlich", 1,
      "Der erste Tag des Jahres. Alles hat zu, viele schlafen lang — in der Nacht davor war Silvester.",
      ["Am Vormittag ist es in den Städten ungewöhnlich still.",
       "Man wünscht sich „ein frohes neues Jahr“ — und zwar die ganze erste Januarwoche, auch im Büro und beim Bäcker.",
       "Viele nehmen sich etwas vor: weniger rauchen, mehr Sport. Das heißt „guter Vorsatz“."],
      [w("Neujahr", "NEU-jahr", "der 1. Januar — ohne Artikel"),
       w("der Vorsatz", "VOR-satz", "was man sich für das neue Jahr vornimmt"),
       w("der Jahreswechsel", "JAH-res-wech-sel", "der Übergang vom alten ins neue Jahr")],
      ["Frohes neues Jahr!", "Ich wünsche dir ein gutes neues Jahr.",
       "Guten Rutsch! (sagt man VOR Silvester, nicht danach)"],
      "„Guten Rutsch“ wünscht man vorher. Am 1. Januar sagt man „frohes neues Jahr“."),

    F("dreikoenige", "Heilige Drei Könige", "HEI-li-ge DREI KÖ-ni-ge", "6. Januar", "regional", 1,
      "In Bayern, Baden-Württemberg und Sachsen-Anhalt ein gesetzlicher Feiertag — im Rest des Landes ein normaler Arbeitstag.",
      ["Kinder ziehen als Sternsinger von Tür zu Tür, singen und sammeln Geld für Kinder in anderen Ländern.",
       "Sie schreiben mit Kreide C+M+B und die Jahreszahl über die Haustür.",
       "Danach kommt der Weihnachtsbaum weg."],
      [w("der Stern", "STERN", "das Symbol, das die Sternsinger tragen"),
       w("die Kreide", "KREI-de", "womit über die Tür geschrieben wird"),
       w("die Spende", "SPEN-de", "Geld, das man für einen guten Zweck gibt")],
      ["Wir spenden gern.", "Bei uns ist heute frei — ich wohne in Bayern."],
      "C+M+B heißt nicht „Caspar, Melchior, Balthasar“, sondern „Christus mansionem benedicat“ — Christus segne dieses Haus."),

    F("karneval", "Karneval, Fasching, Fastnacht", "KAR-ne-val", "Februar oder März, sechs Tage vor Aschermittwoch", "regional", 2,
      "Die „fünfte Jahreszeit“. Am stärksten im Rheinland (Köln, Düsseldorf, Mainz) und im Südwesten. In Norddeutschland merkt man wenig davon.",
      ["Weiberfastnacht (Donnerstag): Frauen schneiden Männern die Krawatte ab. Wer eine gute Krawatte trägt, lässt sie an dem Tag zu Hause.",
       "Rosenmontag: der große Umzug mit Wagen, Musik und Süßigkeiten, die ins Publikum geworfen werden („Kamelle“).",
       "Man verkleidet sich — auch Erwachsene, auch im Büro.",
       "In Köln ruft man „Kölle Alaaf“, in Düsseldorf und Mainz „Helau“."],
      [w("der Umzug", "UM-zug", "der Zug durch die Stadt"),
       w("die Verkleidung", "VER-klei-dung", "das Kostüm"),
       w("der Wagen", "WA-gen", "der geschmückte Anhänger im Umzug"),
       w("die Süßigkeiten", "SÜ-ßig-kei-ten", "was ins Publikum geworfen wird")],
      ["Als was gehst du?", "Ich gehe als Fuchs.", "Helau!", "Kölle Alaaf!"],
      "Rosenmontag ist kein gesetzlicher Feiertag — viele Betriebe im Rheinland geben trotzdem frei."),

    F("valentinstag", "Valentinstag", "VA-len-tins-tag", "14. Februar", "brauch", 2,
      "Ein normaler Arbeitstag. Paare schenken sich Blumen oder eine Kleinigkeit.",
      ["Blumenläden sind an dem Tag voll, rote Rosen teuer.",
       "Man schenkt dem Partner oder der Partnerin etwas — nicht der Familie, nicht Freunden."],
      [w("die Rose", "RO-se", "die typische Blume zum Valentinstag"),
       w("das Geschenk", "Ge-SCHENK", "was man jemandem gibt")],
      ["Alles Liebe zum Valentinstag!"],
      "In Deutschland ist der Tag deutlich kleiner als in den USA oder in Italien."),

    F("karfreitag", "Karfreitag", "KAR-frei-tag", "Freitag vor Ostern", "gesetzlich", 4,
      "Der stillste Tag des Jahres. Christlich: der Todestag von Jesus.",
      ["Ein „stiller Feiertag“: In vielen Bundesländern sind Tanzveranstaltungen und laute Musik in der Öffentlichkeit verboten.",
       "Traditionell isst man kein Fleisch, sondern Fisch.",
       "Läden zu, wie an jedem Feiertag."],
      [w("der Karfreitag", "KAR-frei-tag", "der stille Freitag vor Ostern"),
       w("das Tanzverbot", "TANZ-ver-bot", "an stillen Feiertagen gilt es in vielen Bundesländern"),
       w("der Fisch", "FISCH", "was traditionell auf den Tisch kommt")],
      ["Am Karfreitag haben die Geschäfte zu.", "Gibt es heute Fisch?"],
      "„Kar“ kommt von einem alten Wort für Klage oder Trauer — nicht von „Karte“."),

    F("ostern", "Ostern", "OS-tern", "März oder April, Sonntag und Montag", "gesetzlich", 4,
      "Nach Weihnachten das zweitwichtigste Fest. Christlich: die Auferstehung. Im Alltag: Familie, Frühling, Eier suchen.",
      ["Gründonnerstag und Karfreitag gehen voraus, Ostersonntag und Ostermontag sind frei.",
       "Am Ostersonntag versteckt der Osterhase bunte Eier und Schokolade im Garten oder in der Wohnung — die Kinder suchen sie.",
       "Man färbt Eier, oft schon Tage vorher mit den Kindern.",
       "Viele Familien essen am Sonntag zusammen: Lamm, Braten oder ein großes Frühstück.",
       "Manche gehen in die Osternacht, ein Gottesdienst in der Nacht zum Sonntag.",
       "Osterfeuer: In vielen Dörfern brennt am Abend ein großes Feuer, zu dem alle kommen."],
      [w("der Osterhase", "OS-ter-ha-se", "bringt die Eier"),
       w("das Osterei", "OS-ter-ei", "das bunt gefärbte Ei"),
       w("der Osterstrauß", "OS-ter-strauß", "Zweige mit aufgehängten Eiern"),
       w("das Osterfeuer", "OS-ter-feu-er", "das große Feuer am Osterabend"),
       w("verstecken", "ver-STE-cken", "etwas so hinlegen, dass man es suchen muss"),
       w("färben", "FÄR-ben", "die Eier bunt machen")],
      ["Frohe Ostern!", "Wir suchen nachher Eier im Garten.", "Was habt ihr Ostern vor?"],
      "Vier Tage am Stück frei — von Karfreitag bis Ostermontag. Viele fahren weg, die Autobahnen sind voll."),

    F("erstermai", "Tag der Arbeit", "TAG der AR-beit", "1. Mai", "gesetzlich", 5,
      "Der Tag der Gewerkschaften — und der Tag, an dem der Frühling gefeiert wird.",
      ["Gewerkschaften organisieren Kundgebungen und Reden.",
       "„Tanz in den Mai“: In der Nacht vom 30. April auf den 1. Mai wird gefeiert.",
       "Der Maibaum wird aufgestellt, im Süden ein großes Dorffest.",
       "In manchen Gegenden stellt man der oder dem Liebsten heimlich eine geschmückte Birke vor die Tür."],
      [w("die Gewerkschaft", "Ge-WERK-schaft", "die Organisation, die die Rechte der Arbeitnehmer vertritt"),
       w("der Maibaum", "MAI-baum", "der geschmückte Baum auf dem Dorfplatz"),
       w("die Kundgebung", "KUND-ge-bung", "eine Versammlung mit Reden")],
      ["Am ersten Mai ist frei.", "Gehst du zum Tanz in den Mai?"],
      "Die Walpurgisnacht am 30. April ist die Nacht davor — im Harz ein großes Fest."),

    F("muttertag", "Muttertag", "MUT-ter-tag", "zweiter Sonntag im Mai", "brauch", 5,
      "Kein Feiertag, aber fast alle machen mit.",
      ["Kinder basteln in der Kita etwas, Erwachsene schenken Blumen oder laden zum Essen ein.",
       "Restaurants sind an dem Sonntag oft komplett ausgebucht — rechtzeitig reservieren."],
      [w("die Mutter", "MUT-ter", ""), w("basteln", "BAS-teln", "etwas mit der Hand herstellen"),
       w("reservieren", "re-ser-VIE-ren", "einen Tisch vorbestellen")],
      ["Alles Gute zum Muttertag!", "Ich möchte einen Tisch für vier Personen reservieren."],
      "Den Vatertag gibt es auch — er fällt auf Christi Himmelfahrt."),

    F("himmelfahrt", "Christi Himmelfahrt / Vatertag", "HIM-mel-fahrt", "40 Tage nach Ostern, immer ein Donnerstag", "gesetzlich", 5,
      "Ein gesetzlicher Feiertag mit zwei Gesichtern: kirchlich Himmelfahrt, im Alltag Vatertag.",
      ["Männergruppen ziehen mit einem Bollerwagen los, oft mit Bier.",
       "Viele Familien machen einen Ausflug, weil ohnehin frei ist.",
       "Der Freitag danach wird gern als Brückentag genommen — dann hat man vier Tage."],
      [w("der Ausflug", "AUS-flug", "ein Tag draußen, außerhalb der Stadt"),
       w("der Bollerwagen", "BOL-ler-wa-gen", "der Handwagen, den man hinter sich herzieht"),
       w("der Brückentag", "BRÜ-cken-tag", "der Arbeitstag zwischen Feiertag und Wochenende")],
      ["Ich nehme Freitag als Brückentag.", "Wir machen einen Ausflug."],
      "„Brückentag“ ist ein sehr nützliches Wort: Wer ihn früh beantragt, bekommt ihn."),

    F("pfingsten", "Pfingsten", "PFINGS-ten", "50 Tage nach Ostern, Sonntag und Montag", "gesetzlich", 6,
      "Noch ein langes Wochenende. Kirchlich das Fest des Heiligen Geistes, im Alltag vor allem: frei.",
      ["Pfingstmontag ist gesetzlicher Feiertag, Läden zu.",
       "Viele Vereine und Dörfer machen an Pfingsten ihr Fest.",
       "In einigen Bundesländern gibt es Pfingstferien für die Schulen."],
      [w("Pfingsten", "PFINGS-ten", "das Fest 50 Tage nach Ostern — ohne Artikel"), w("der Verein", "Ver-EIN", "eine Gruppe, die sich regelmäßig trifft — Sport, Musik, Schützen"),
       w("die Ferien", "FE-ri-en", "die schulfreie Zeit")],
      ["Frohe Pfingsten!", "Habt ihr Pfingstferien?"],
      "Das Wort kommt aus dem Griechischen: „pentekoste“ heißt „der fünfzigste“."),

    F("einheit", "Tag der Deutschen Einheit", "TAG der DEUT-schen EIN-heit", "3. Oktober", "gesetzlich", 10,
      "Der Nationalfeiertag. Er erinnert an den 3. Oktober 1990, den Tag, an dem die DDR und die Bundesrepublik wieder ein Land wurden.",
      ["Jedes Jahr richtet ein anderes Bundesland das zentrale Fest aus.",
       "Es gibt Bürgerfeste, Musik und offene Türen in Ministerien.",
       "Anders als in vielen Ländern: keine Militärparade, wenig Fahnen. Das hat historische Gründe."],
      [w("die Einheit", "EIN-heit", "dass etwas wieder eins ist"),
       w("die Mauer", "MAU-er", "die Berliner Mauer, 1961 bis 1989"),
       w("die Wiedervereinigung", "WIE-der-ver-EI-ni-gung", "die Vereinigung von Ost und West 1990"),
       w("das Bundesland", "BUN-des-land", "eines der 16 Länder Deutschlands")],
      ["Am 3. Oktober ist frei.", "Wie war das damals mit der Mauer?"],
      "Der Mauerfall war am 9. November 1989 — gefeiert wird aber der 3. Oktober, weil der 9. November in der deutschen Geschichte auch ein sehr dunkles Datum ist."),

    F("erntedank", "Erntedankfest", "ERN-te-dank-fest", "erster Sonntag im Oktober", "brauch", 10,
      "Ein Kirchenfest, das auf dem Land noch groß gefeiert wird.",
      ["Die Kirchen werden mit Obst, Gemüse und Getreide geschmückt.",
       "Danach werden die Gaben an Bedürftige weitergegeben.",
       "Auf dem Dorf oft mit Umzug und Erntekrone."],
      [w("die Ernte", "ERN-te", "was im Jahr auf dem Feld gewachsen ist"),
       w("das Getreide", "Ge-TREI-de", "Weizen, Roggen, Gerste"),
       w("danken", "DAN-ken", "Danke sagen")],
      ["Bei uns wird Erntedank groß gefeiert."],
      "In den Städten bekommt man davon meistens nichts mit."),

    F("martin", "Sankt Martin", "SANKT MAR-tin", "11. November", "brauch", 11,
      "Ein Fest für Kinder — und eines der schönsten Bilder des deutschen Herbstes.",
      ["Kinder basteln Laternen und ziehen abends singend durch die Straßen, oft hinter einem Reiter auf einem Pferd.",
       "Danach gibt es ein Martinsfeuer und einen „Weckmann“ — ein Gebäck in Männerform mit einer Tonpfeife.",
       "Die Geschichte: Martin teilte seinen Mantel mit einem frierenden Bettler."],
      [w("die Laterne", "La-TER-ne", "das Licht, das die Kinder tragen"),
       w("der Umzug", "UM-zug", "der Zug durch die Straßen"),
       w("teilen", "TEI-len", "etwas mit jemandem gemeinsam haben"),
       w("der Mantel", "MAN-tel", "die warme Jacke")],
      ["Wir gehen Laterne laufen.", "Ich geh mit meiner Laterne …"],
      "Am selben Tag um 11:11 Uhr beginnt im Rheinland offiziell die Karnevalssaison."),

    F("advent", "Advent und Weihnachtsmarkt", "Ad-VENT", "die vier Sonntage vor Weihnachten", "brauch", 12,
      "Die vier Wochen vor Weihnachten — für viele die schönste Zeit des Jahres.",
      ["Der Adventskranz hat vier Kerzen: Jeden Sonntag wird eine mehr angezündet.",
       "Kinder bekommen einen Adventskalender mit 24 Türchen.",
       "Ab Ende November öffnen überall Weihnachtsmärkte: Glühwein, gebrannte Mandeln, Bratwurst, Holzbuden, Musik.",
       "Man geht dort nicht zum Einkaufen hin, sondern um sich mit Leuten zu treffen — eine gute Gelegenheit, Kolleg:innen näher kennenzulernen.",
       "Auf dem Glühweinbecher liegt Pfand: Man zahlt zwei, drei Euro mehr und bekommt sie zurück, wenn man den Becher zurückbringt."],
      [w("der Advent", "Ad-VENT", "die Zeit vor Weihnachten"),
       w("der Adventskranz", "Ad-VENTS-kranz", "der Kranz mit den vier Kerzen"),
       w("der Adventskalender", "Ad-VENTS-ka-len-der", "24 Türchen bis Heiligabend"),
       w("der Glühwein", "GLÜH-wein", "heißer, gewürzter Wein"),
       w("der Weihnachtsmarkt", "WEIH-nachts-markt", "der Markt in der Adventszeit"),
       w("das Pfand", "PFAND", "das Geld, das man für Becher oder Flasche zurückbekommt")],
      ["Gehen wir auf den Weihnachtsmarkt?", "Einen Glühwein, bitte.",
       "Ohne Alkohol, bitte — einen Kinderpunsch.", "Ist da Pfand drauf?"],
      "Kinderpunsch ist Glühwein ohne Alkohol. Danach fragen ist völlig normal, niemand schaut komisch."),

    F("nikolaus", "Nikolaustag", "NI-ko-laus-tag", "6. Dezember", "brauch", 12,
      "Kein Feiertag, aber für Kinder ein großer Tag.",
      ["Am Abend des 5. Dezember stellen Kinder einen geputzten Stiefel vor die Tür.",
       "Am Morgen liegen Süßigkeiten, Nüsse und Mandarinen darin.",
       "In manchen Gegenden kommt der Nikolaus persönlich, mit einem Buch, in dem steht, was das Kind gut gemacht hat."],
      [w("der Nikolaus", "NI-ko-laus", "der Heilige, der die Geschenke bringt"),
       w("der Stiefel", "STIE-fel", "der Schuh, den man hinausstellt"),
       w("putzen", "PUT-zen", "sauber machen"),
       w("die Nuss", "NUSS", "liegt im Nikolausstiefel")],
      ["Hast du deinen Stiefel rausgestellt?", "Der Nikolaus war da!"],
      "Der Nikolaus ist nicht der Weihnachtsmann. Der Nikolaus kommt am 6. Dezember, der Weihnachtsmann an Heiligabend."),

    F("weihnachten", "Weihnachten", "WEIH-nach-ten", "24., 25. und 26. Dezember", "gesetzlich", 12,
      "Das wichtigste Familienfest des Jahres. Wer neu in Deutschland ist, merkt es vor allem daran, dass drei Tage lang praktisch nichts geöffnet hat.",
      ["24. Dezember (Heiligabend): kein gesetzlicher Feiertag, aber die Läden schließen mittags, viele haben ab mittags frei. Abends gibt es Geschenke — anders als in vielen Ländern, wo erst am 25. verteilt wird.",
       "Typisch am Heiligabend: ein einfaches Essen (Würstchen mit Kartoffelsalat), dann der Baum, dann die Bescherung. Viele gehen in die Christmette.",
       "25. und 26. Dezember: gesetzliche Feiertage, alles zu. Das große Essen mit der Familie — Gans, Ente oder Braten.",
       "Der Weihnachtsbaum wird oft erst am 24. geschmückt und bleibt bis in den Januar stehen.",
       "Wichtig für den Alltag: Am 23. Dezember sind die Supermärkte extrem voll. Wer am 24. noch einkaufen will, sollte vormittags da sein.",
       "Man schenkt auch Nachbarn oder Kolleg:innen eine Kleinigkeit — Plätzchen, Schokolade. Teuer muss es nicht sein."],
      [w("Weihnachten", "WEIH-nach-ten", "das Fest am 24. bis 26. Dezember — ohne Artikel"),
       w("der Heiligabend", "HEI-lig-a-bend", "der 24. Dezember"),
       w("die Bescherung", "Be-SCHE-rung", "das Auspacken der Geschenke"),
       w("der Weihnachtsbaum", "WEIH-nachts-baum", "der geschmückte Tannenbaum"),
       w("die Plätzchen", "PLÄTZ-chen", "die kleinen Weihnachtskekse"),
       w("die Krippe", "KRIP-pe", "die Darstellung der Weihnachtsgeschichte mit Figuren"),
       w("der Weihnachtsmann", "WEIH-nachts-mann", "bringt in Nord- und Ostdeutschland die Geschenke"),
       w("das Christkind", "CHRIST-kind", "bringt sie in Süddeutschland")],
      ["Frohe Weihnachten!", "Schöne Feiertage!", "Was schenkst du deinen Eltern?",
       "Wir feiern nicht Weihnachten, aber ich wünsche euch schöne Tage."],
      "Man muss nicht christlich sein, um mitzufeiern — und man muss auch nicht mitfeiern. „Schöne Feiertage“ ist der Gruß, der für alle passt."),

    F("silvester", "Silvester", "Sil-VES-ter", "31. Dezember", "brauch", 12,
      "Der letzte Tag des Jahres. Kein Feiertag — aber ab nachmittags arbeitet kaum noch jemand.",
      ["Um Mitternacht wird geböllert: Feuerwerk, Raketen, Knaller. Verkauft wird es nur an drei Tagen im Jahr.",
       "Man stößt mit Sekt an und wünscht sich ein gutes neues Jahr.",
       "„Dinner for One“ läuft in mehreren Sendern — ein englischer Sketch, den in England fast niemand kennt.",
       "Bleigießen (heute aus Wachs): Man gießt eine Figur und deutet, was sie über das nächste Jahr sagt.",
       "Achtung: In vielen Innenstädten ist Feuerwerk inzwischen verboten. Und Tiere leiden darunter sehr."],
      [w("Silvester", "Sil-VES-ter", "der 31. Dezember — ohne Artikel"),
       w("das Feuerwerk", "FEU-er-werk", "die Raketen um Mitternacht"),
       w("anstoßen", "AN-sto-ßen", "die Gläser aneinanderhalten"),
       w("der Sekt", "SEKT", "der Schaumwein"),
       w("die Rakete", "Ra-KE-te", "steigt hoch und knallt")],
      ["Guten Rutsch!", "Prost Neujahr!", "Was macht ihr Silvester?", "Auf ein gutes neues Jahr!"],
      "„Guten Rutsch“ sagt man in den Tagen VOR Silvester. Es kommt wahrscheinlich vom jiddischen „Rosch“ (Anfang), nicht vom Rutschen."),

    F("geburtstag", "Geburtstag", "Ge-BURTS-tag", "das ganze Jahr", "brauch", 0,
      "Kein Feiertag, aber eine Regel, über die fast alle Zugezogenen einmal stolpern.",
      ["Man gratuliert NIEMALS vor dem eigentlichen Tag. Das bringt Unglück — und selbst wer nicht abergläubisch ist, hält sich daran.",
       "Das Geburtstagskind lädt selbst ein und zahlt oft auch — im Büro bringt man den Kuchen selbst mit.",
       "Runde Geburtstage (30, 40, 50) werden groß gefeiert.",
       "Zum 18. wird man volljährig: Führerschein, Wahlrecht, alles."],
      [w("der Geburtstag", "Ge-BURTS-tag", "der Jahrestag der Geburt"),
       w("gratulieren", "gra-tu-LIE-ren", "jemandem zum Geburtstag alles Gute wünschen"),
       w("einladen", "EIN-la-den", "jemanden bitten zu kommen — und meistens auch zahlen"),
       w("volljährig", "VOLL-jäh-rig", "ab 18 Jahren")],
      ["Herzlichen Glückwunsch zum Geburtstag!", "Alles Gute!",
       "Ich bringe morgen Kuchen mit, ich habe Geburtstag."],
      "Vorher gratulieren gilt als Unglück. Lieber einen Tag zu spät als einen zu früh."),
  ];

  const FESTE_IT = [
    F("capodanno", "Capodanno", "ca-po-DAN-no", "1. Januar", "gesetzlich", 1,
      "Der Neujahrstag. In der Nacht davor („San Silvestro“) wird groß gefeiert.",
      ["Zum Mitternachtsessen gehören Linsen („lenticchie“) — sie sollen Geld bringen.",
       "Dazu „cotechino“ oder „zampone“, eine kräftige Wurst.",
       "In manchen Gegenden trägt man rote Unterwäsche, das bringt Glück."],
      [w("il capodanno", "ca-po-DAN-no", "Neujahr"),
       w("le lenticchie", "len-TIC-chie", "die Linsen"),
       w("il brindisi", "BRIN-di-si", "das Anstoßen")],
      ["Buon anno!", "Auguri!", "Cin cin!"],
      "Anders als in Deutschland isst man zu Neujahr fast überall dasselbe: Linsen."),

    F("befana", "Epifania — La Befana", "e-pi-fa-NI-a", "6. Januar", "gesetzlich", 1,
      "Der Tag, an dem die Weihnachtszeit endet — und für Kinder fast so wichtig wie Weihnachten.",
      ["Die Befana ist eine alte Frau auf einem Besen. Sie bringt braven Kindern Süßigkeiten und den anderen Kohle — heute Zuckerkohle.",
       "Die Kinder hängen einen Strumpf („la calza“) auf.",
       "Sprichwort: „L'Epifania tutte le feste porta via“ — Epiphanias trägt alle Feste fort."],
      [w("la Befana", "Be-FA-na", "die gute Hexe"),
       w("la calza", "CAL-za", "der Strumpf"),
       w("il carbone", "car-BO-ne", "die Kohle")],
      ["Che cosa ti ha portato la Befana?"],
      "Das deutsche Sternsingen und die italienische Befana fallen auf denselben Tag."),

    F("carnevale", "Carnevale", "car-ne-VA-le", "Februar", "brauch", 2,
      "Am berühmtesten in Venedig mit den Masken, am buntesten in Viareggio mit den Wagen.",
      ["Kinder verkleiden sich und werfen Konfetti — das Wort ist italienisch.",
       "Typisches Gebäck: „le chiacchiere“, dünn und frittiert.",
       "Der letzte Tag heißt „martedì grasso“ — fetter Dienstag."],
      [w("la maschera", "MA-sche-ra", "die Maske"),
       w("i coriandoli", "co-RIAN-do-li", "das Konfetti"),
       w("le chiacchiere", "chiac-CHIE-re", "das Karnevalsgebäck")],
      ["Di che cosa ti vesti?", "Buon carnevale!"],
      "„Carnevale“ kommt von „carne vale“ — Fleisch, lebe wohl. Danach beginnt die Fastenzeit."),

    F("pasqua", "Pasqua e Pasquetta", "PA-squa", "März oder April", "gesetzlich", 4,
      "Ostern, und am Montag „Pasquetta“ — der Tag, an dem ganz Italien ins Grüne fährt.",
      ["Statt Eiern gibt es eine große Schokoladen-Ei mit Überraschung drin.",
       "Die „colomba“ ist ein Kuchen in Taubenform.",
       "Sprichwort: „Natale con i tuoi, Pasqua con chi vuoi“ — Weihnachten mit der Familie, Ostern mit wem du willst.",
       "An Pasquetta macht man ein Picknick („la scampagnata“)."],
      [w("la Pasqua", "PA-squa", "Ostern"),
       w("l'uovo di cioccolato", "UO-vo", "das Schokoladenei"),
       w("la colomba", "co-LOM-ba", "der Osterkuchen in Taubenform")],
      ["Buona Pasqua!", "Che fate a Pasquetta?"],
      "Das Schoko-Ei ist groß und hohl, mit einem kleinen Geschenk darin."),

    F("liberazione", "Festa della Liberazione", "li-be-ra-ZIO-ne", "25. April", "gesetzlich", 4,
      "Der Tag der Befreiung vom Faschismus 1945.",
      ["Es gibt Kundgebungen und Konzerte.",
       "Das Lied „Bella ciao“ gehört zu diesem Tag."],
      [w("la liberazione", "li-be-ra-ZIO-ne", "die Befreiung"),
       w("la resistenza", "re-si-STEN-za", "der Widerstand")],
      ["Il venticinque aprile è festa."],
      "Zusammen mit dem 1. Mai und dem 2. Juni einer der drei bürgerlichen Feiertage Italiens."),

    F("repubblica", "Festa della Repubblica", "re-PUB-bli-ca", "2. Juni", "gesetzlich", 6,
      "Der Nationalfeiertag. 1946 stimmte Italien für die Republik und gegen die Monarchie.",
      ["In Rom gibt es eine Parade, die Flugstaffel zieht die Flagge in den Himmel.",
       "Anders als Deutschland feiert Italien mit Militärparade."],
      [w("la repubblica", "re-PUB-bli-ca", "die Republik"),
       w("la bandiera", "ban-DIE-ra", "die Flagge")],
      ["Il due giugno è la festa nazionale."],
      ""),

    F("ferragosto", "Ferragosto", "fer-ra-GO-sto", "15. August", "gesetzlich", 8,
      "Der Höhepunkt des italienischen Sommers — und der Tag, an dem das Land stillsteht.",
      ["Fast alle sind im Urlaub, viele Geschäfte und Werkstätten haben die ganze Woche zu.",
       "Man geht ans Meer, grillt, isst mit der Familie.",
       "Wer in dieser Woche etwas erledigen muss, hat Pech."],
      [w("il Ferragosto", "fer-ra-GO-sto", "der 15. August"),
       w("le ferie", "FE-rie", "der Urlaub"),
       w("chiuso per ferie", "CHIU-so", "wegen Urlaub geschlossen")],
      ["Buon Ferragosto!", "Siamo chiusi per ferie."],
      "„Chiuso per ferie“ steht im August an sehr vielen Türen."),

    F("natale", "Natale", "na-TA-le", "25. und 26. Dezember", "gesetzlich", 12,
      "Weihnachten — das große Familienfest, wie in Deutschland, aber anders im Ablauf.",
      ["Am 24. abends („la Vigilia“) isst man traditionell Fisch, kein Fleisch.",
       "Die Geschenke gibt es meist am Morgen des 25., nicht am Abend des 24.",
       "Der „presepe“ (die Krippe) ist oft wichtiger als der Baum. In Neapel gibt es eine ganze Straße dafür.",
       "Panettone (aus Mailand) und Pandoro (aus Verona) — über den Vorrang streitet man jedes Jahr.",
       "Der 26. Dezember heißt „Santo Stefano“ und ist auch frei."],
      [w("il Natale", "na-TA-le", "Weihnachten"),
       w("il presepe", "pre-SE-pe", "die Krippe"),
       w("il panettone", "pa-net-TO-ne", "der Weihnachtskuchen aus Mailand"),
       w("i regali", "re-GA-li", "die Geschenke"),
       w("la Vigilia", "vi-GI-lia", "der Heilige Abend")],
      ["Buon Natale!", "Tanti auguri!", "Buone feste!"],
      "„Natale con i tuoi“ — Weihnachten verbringt man mit der Familie, da gibt es wenig Diskussion."),
  ];

  /* =========================================================
     DER ALLTAG — das Ungeschriebene
     ========================================================= */
  const A = (id, titel, kurz, punkte, woerter, saetze, warnung) =>
    ({ id, titel, kurz, punkte, woerter, saetze, warnung });

  const ALLTAG_DE = [
    A("puenktlichkeit", "Pünktlichkeit",
      "Pünktlich heißt: zur vereinbarten Minute da. Fünf Minuten zu spät sind schon spät.",
      ["Bei einem Termin beim Arzt, Amt oder Vorstellungsgespräch ist man fünf bis zehn Minuten VOR der Zeit da.",
       "Bei einer privaten Einladung zum Essen kommt man pünktlich. Bei einer Party darf man später kommen.",
       "Wer sich verspätet, schreibt oder ruft an — auch bei fünf Minuten. Das ist wichtiger als die Verspätung selbst.",
       "„Akademisches Viertel“: An der Universität beginnt eine Vorlesung um „10 Uhr c.t.“ tatsächlich um 10:15."],
      [w("die Verspätung", "Ver-SPÄ-tung", "wenn man zu spät kommt"),
       w("pünktlich", "PÜNKT-lich", "genau zur richtigen Zeit"),
       w("der Termin", "Ter-MIN", "die feste Verabredung")],
      ["Entschuldigen Sie die Verspätung.", "Ich komme zehn Minuten später, tut mir leid.",
       "Ich bin gleich da."],
      "Ein Termin, zu dem man nicht kommt und nicht absagt, kann Geld kosten — beim Arzt und beim Friseur."),

    A("ruhezeiten", "Ruhezeiten und der Sonntag",
      "Zwischen 22 und 6 Uhr ist Nachtruhe, sonntags den ganzen Tag Ruhe. Das steht in der Hausordnung und gilt wirklich.",
      ["Nach 22 Uhr: keine Waschmaschine, kein Staubsauger, keine laute Musik, nicht duschen mit lautem Rohr — Regeln stehen in der Hausordnung.",
       "Mittagsruhe von 13 bis 15 Uhr gibt es in vielen Häusern noch.",
       "Sonntags wird nicht gebohrt, nicht gemäht, nicht gewaschen. Auch nicht das Auto.",
       "Wenn eine Feier lauter wird: vorher einen Zettel ins Treppenhaus hängen. Das wirkt besser als jede Entschuldigung danach.",
       "Läden haben sonntags zu — außer am Bahnhof, an der Tankstelle und beim Bäcker für ein paar Stunden."],
      [w("die Ruhezeit", "RU-he-zeit", "die Zeit, in der es leise sein muss"),
       w("die Hausordnung", "HAUS-ord-nung", "die Regeln im Mietshaus"),
       w("die Nachtruhe", "NACHT-ru-he", "ab 22 Uhr"),
       w("bohren", "BOH-ren", "ein Loch in die Wand machen")],
      ["Entschuldigung, wir feiern heute Abend — es könnte etwas lauter werden.",
       "Ab wann gilt hier die Nachtruhe?"],
      "Sonntags einkaufen geht nicht. Wer freitags vergisst einzukaufen, hat am Sonntag ein Problem."),

    A("muell", "Mülltrennung",
      "Vier bis fünf verschiedene Tonnen. Wer falsch trennt, bekommt Ärger mit dem Hausmeister — und manchmal wird die Tonne nicht geleert.",
      ["Blaue Tonne: Papier und Pappe. Keine beschichteten Kartons, kein Papier mit Essensresten.",
       "Gelbe Tonne oder gelber Sack: Verpackungen aus Plastik, Metall und Verbund — Joghurtbecher, Konservendosen, Tetrapak.",
       "Braune Tonne (Biotonne): Essensreste, Schalen, Kaffeesatz, Gartenabfälle.",
       "Schwarze/graue Tonne (Restmüll): alles andere.",
       "Glas kommt zum Container — getrennt nach weiß, grün und braun. Und nicht nach 20 Uhr oder sonntags, das ist zu laut.",
       "Batterien, Elektrogeräte, Farben und Medikamente gehören NICHT in den Hausmüll. Dafür gibt es den Wertstoffhof."],
      [w("die Mülltonne", "MÜLL-ton-ne", "der große Behälter"),
       w("trennen", "TREN-nen", "auseinanderhalten"),
       w("die Verpackung", "Ver-PA-ckung", "was um das Produkt herum ist"),
       w("der Restmüll", "REST-müll", "alles, was in keine andere Tonne gehört"),
       w("der Wertstoffhof", "WERT-stoff-hof", "wo man Sondermüll abgibt")],
      ["In welche Tonne kommt das?", "Wann wird die Biotonne geleert?"],
      "Im Zweifel fragen. Die Nachbarn erklären es gern — sie wollen, dass es richtig gemacht wird."),

    A("pfand", "Pfand",
      "Auf Flaschen und Dosen liegt Geld. Man bekommt es zurück, wenn man sie in den Automaten steckt.",
      ["Einwegflaschen aus Plastik und Dosen: 25 Cent.",
       "Mehrweg-Glasflaschen: 8 oder 15 Cent. Bierkästen: bis zu 3,10 Euro.",
       "Der Automat steht im Supermarkt. Er druckt einen Bon, den man an der Kasse einlöst oder beim Einkauf verrechnet.",
       "Nicht jede Flasche hat Pfand: Saft- und Weinflaschen oft nicht. Das Zeichen steht auf dem Etikett.",
       "Wer die Flasche neben den Mülleimer stellt, statt sie hineinzuwerfen, macht es jemandem leichter, der sie sammelt. Das ist ein stiller Brauch."],
      [w("das Pfand", "PFAND", "das Geld, das man zurückbekommt"),
       w("der Automat", "Au-to-MAT", "das Gerät, in das man die Flaschen steckt"),
       w("der Bon", "BON", "der kleine Zettel mit dem Betrag"),
       w("die Mehrwegflasche", "MEHR-weg-fla-sche", "die Flasche, die wieder befüllt wird")],
      ["Ist da Pfand drauf?", "Wo ist der Pfandautomat?", "Den Bon bitte auf den Einkauf."],
      "Ein Einkaufswagen braucht meistens ein Ein-Euro-Stück als Pfand. Man bekommt es zurück."),

    A("termine", "Termine und Fristen",
      "In Deutschland läuft fast alles über Termine — und über Fristen, die man einhalten muss.",
      ["Zum Amt, zum Arzt, zur Bank: vorher einen Termin machen. Ohne Termin wartet man lange oder wird weggeschickt.",
       "Anmeldung nach dem Umzug: innerhalb von zwei Wochen.",
       "Krankmeldung beim Arbeitgeber: am ersten Tag, meist vor Arbeitsbeginn. Ab dem vierten Tag braucht man ein Attest — oft steht es aber schon ab Tag eins im Arbeitsvertrag.",
       "Kündigungsfristen bei Wohnung, Handy und Versicherung: fast immer drei Monate. Wer zu spät kündigt, zahlt ein Jahr weiter.",
       "Widerspruch gegen einen Bescheid: meistens vier Wochen. Das Datum steht im Brief unter „Rechtsbehelfsbelehrung“."],
      [w("die Frist", "FRIST", "die Zeit, bis zu der etwas erledigt sein muss"),
       w("kündigen", "KÜN-di-gen", "einen Vertrag beenden"),
       w("der Bescheid", "Be-SCHEID", "der offizielle Brief einer Behörde"),
       w("der Widerspruch", "WI-der-spruch", "wenn man mit einem Bescheid nicht einverstanden ist"),
       w("die Krankmeldung", "KRANK-mel-dung", "die Nachricht, dass man krank ist")],
      ["Ich möchte einen Termin vereinbaren.", "Bis wann muss das eingereicht sein?",
       "Ich melde mich krank."],
      "Behördenbriefe sofort öffnen, auch wenn sie unangenehm aussehen. Die Frist läuft ab dem Datum im Brief."),

    A("hand", "Begrüßen: Hand, Abstand, Blick",
      "Im Beruf gibt man die Hand. Privat umarmt man Freunde. Fremde fasst man nicht an.",
      ["Händedruck: fest, aber nicht zerquetschend, dazu Blickkontakt. Ein schlaffer Händedruck fällt negativ auf.",
       "Im Büro reicht bei einer größeren Runde ein Nicken in die Runde und ein „Guten Morgen“.",
       "Küsschen auf die Wange gibt es nur unter Freunden — und nicht überall.",
       "Blickkontakt beim Sprechen gilt als ehrlich. Wer wegschaut, wirkt unsicher — das ist in anderen Kulturen genau umgekehrt, aber hier ist es so.",
       "Abstand: etwa eine Armlänge. Näher ist vielen unangenehm."],
      [w("der Händedruck", "HÄN-de-druck", "das Schütteln der Hand"),
       w("der Blickkontakt", "BLICK-kon-takt", "wenn man sich in die Augen sieht"),
       w("die Umarmung", "Um-AR-mung", "wenn man jemanden in den Arm nimmt")],
      ["Freut mich!", "Angenehm.", "Guten Morgen zusammen!"],
      "Wer aus religiösen Gründen einer Person des anderen Geschlechts nicht die Hand gibt, kann das kurz und freundlich sagen: „Ich gebe aus religiösen Gründen nicht die Hand, aber es freut mich sehr.“ Das wird fast immer akzeptiert."),

    A("smalltalk", "Worüber man redet — und worüber nicht",
      "Es gibt Themen, mit denen man jedes Gespräch anfangen kann, und solche, die als sehr privat gelten.",
      ["Geht immer: Wetter, Urlaub, Essen, Fußball, die Bahn (und wie unpünktlich sie ist), Kinder, Haustiere, das Wochenende.",
       "Heikel: Gehalt, Miete, Alter, Gewicht, Religion, Krankheit, für wen jemand wählt.",
       "Nach dem Gehalt fragt man nicht — auch nicht unter Kolleg:innen, obwohl es erlaubt wäre.",
       "„Wie geht's?“ ist eine echte Frage, keine Floskel wie im Englischen. Eine kurze ehrliche Antwort wird erwartet: „Ganz gut, und dir?“",
       "Kritik wird direkt gesagt. Das ist nicht unfreundlich gemeint — im Gegenteil: Wer schweigt, gilt als unehrlich."],
      [w("der Smalltalk", "SMALL-talk", "das lockere Gespräch"),
       w("das Gehalt", "Ge-HALT", "das Geld, das man im Monat verdient"),
       w("die Floskel", "FLOS-kel", "ein Satz, der nichts bedeutet"),
       w("heikel", "HEI-kel", "schwierig, sensibel")],
      ["Schönes Wetter heute, oder?", "Wie war dein Wochenende?",
       "Das sage ich lieber nicht, das ist mir zu privat."],
      "Deutsche Direktheit ist kein schlechtes Benehmen. „Das finde ich nicht gut“ heißt genau das — und nicht mehr."),

    A("wohnen", "Im Mietshaus",
      "Wer zur Miete wohnt, teilt sich Treppenhaus, Keller, Waschküche und manchmal einen Garten. Dafür gibt es Regeln.",
      ["Die Hausordnung hängt im Flur oder steht im Mietvertrag. Sie zu lesen lohnt sich.",
       "Kehrwoche (vor allem in Baden-Württemberg): Jede Partei ist reihum dran, Treppenhaus und Gehweg zu putzen.",
       "Im Winter muss der Gehweg geräumt und gestreut werden — oft sind die Mieter dafür zuständig. Wer stürzt, kann Schadenersatz verlangen.",
       "Das Treppenhaus ist ein Fluchtweg: Kinderwagen, Schuhe und Kartons dürfen dort meistens nicht stehen.",
       "Lüften: dreimal am Tag für fünf bis zehn Minuten das Fenster ganz auf, nicht kippen. Sonst gibt es Schimmel — und dafür haftet der Mieter."],
      [w("die Hausordnung", "HAUS-ord-nung", "die Regeln im Haus"),
       w("die Kehrwoche", "KEHR-wo-che", "wenn man mit Putzen dran ist"),
       w("der Streudienst", "STREU-dienst", "das Streuen bei Glätte"),
       w("lüften", "LÜF-ten", "frische Luft hereinlassen"),
       w("der Schimmel", "SCHIM-mel", "der dunkle Belag an feuchten Wänden")],
      ["Wann bin ich mit der Kehrwoche dran?", "Darf der Kinderwagen im Flur stehen?"],
      "Stoßlüften statt Fenster kippen — das spart Heizkosten und verhindert Schimmel."),

    A("arbeit", "Am Arbeitsplatz",
      "Ein paar Dinge, die niemand erklärt, die aber alle wissen.",
      ["Feierabend ist Feierabend. Nach Dienstschluss ruft man nicht an und erwartet keine Antwort auf E-Mails.",
       "Urlaub wird lange vorher beantragt — bei vielen Betrieben im Januar für das ganze Jahr.",
       "Wer krank ist, bleibt zu Hause. Krank zur Arbeit zu kommen gilt nicht als fleißig, sondern als rücksichtslos.",
       "Duzen oder siezen: Am ersten Tag zuhören, wie die anderen miteinander reden. Die Chefin oder der Chef bietet das Du an, nicht umgekehrt.",
       "Zum Geburtstag bringt das Geburtstagskind selbst Kuchen mit.",
       "Die Mittagspause ist echte Pause — man geht weg vom Schreibtisch."],
      [w("der Feierabend", "FEI-er-a-bend", "das Ende des Arbeitstages"),
       w("der Urlaubsantrag", "UR-laubs-an-trag", "der Zettel, mit dem man Urlaub beantragt"),
       w("die Probezeit", "PRO-be-zeit", "die ersten sechs Monate, in denen schneller gekündigt werden kann"),
       w("der Betriebsrat", "Be-TRIEBS-rat", "die gewählte Vertretung der Beschäftigten")],
      ["Schönen Feierabend!", "Ich würde gern Urlaub beantragen.",
       "Ich bin heute krank, ich schaffe es nicht."],
      "Der Betriebsrat hilft bei Problemen mit dem Arbeitgeber — kostenlos und vertraulich."),

    A("verkehr", "Unterwegs",
      "Regeln, die kaum jemand aufschreibt, die aber jeder einhält.",
      ["Bei Rot bleibt man stehen — auch nachts, auch wenn kein Auto kommt. Besonders, wenn Kinder zusehen.",
       "Radwege gehören den Rädern. Wer darauf spazieren geht, wird angeklingelt.",
       "Im Bus und in der Bahn: Fahrschein VOR dem Einsteigen kaufen und entwerten. Kontrollen kommen ohne Vorwarnung, „erhöhtes Beförderungsentgelt“ sind 60 Euro.",
       "Rechts stehen, links gehen — auf der Rolltreppe.",
       "Man lässt erst aussteigen, dann steigt man ein.",
       "Der Platz für Rollstühle, Kinderwagen und ältere Menschen wird freigemacht, wenn jemand ihn braucht."],
      [w("der Fahrschein", "FAHR-schein", "die Fahrkarte"),
       w("entwerten", "ent-WER-ten", "am Automaten abstempeln"),
       w("der Radweg", "RAD-weg", "der Weg für Fahrräder"),
       w("die Rolltreppe", "ROLL-trep-pe", "rechts stehen, links gehen")],
      ["Einmal Einzelfahrt, bitte.", "Entschuldigung, ist der Platz frei?",
       "Darf ich mal durch?"],
      "Schwarzfahren ist in Deutschland kein Kavaliersdelikt: Beim dritten Mal wird es eine Straftat."),

    A("geld", "Geld und Rechnungen",
      "Deutschland zahlt mehr bar als die Nachbarländer — und liebt den Überweisungsbeleg.",
      ["Kleine Läden, Bäcker und Kioske nehmen oft nur Bargeld oder EC-Karte, keine Kreditkarte.",
       "Trinkgeld: fünf bis zehn Prozent, aufgerundet. Man sagt den Gesamtbetrag beim Zahlen: „Macht 18,50? Dann 20.“",
       "Rechnungen kommen per Post oder Mail und werden überwiesen. Lastschrift („Einzugsermächtigung“) ist bequem und üblich.",
       "Mahnung: Wer eine Rechnung nicht zahlt, bekommt eine Erinnerung, dann eine Mahnung mit Gebühr. Nicht ignorieren — auch dann nicht, wenn man nicht zahlen kann. Anrufen und eine Ratenzahlung vereinbaren geht fast immer.",
       "Der Rundfunkbeitrag (18,36 Euro im Monat, Stand 2025) wird pro Wohnung fällig, nicht pro Person — auch wenn man kein Fernsehen hat."],
      [w("das Bargeld", "BAR-geld", "Münzen und Scheine"),
       w("die Überweisung", "Ü-ber-WEI-sung", "Geld von Konto zu Konto"),
       w("die Mahnung", "MAH-nung", "die Aufforderung, endlich zu zahlen"),
       w("die Ratenzahlung", "RA-ten-zah-lung", "in kleinen Beträgen zahlen"),
       w("das Trinkgeld", "TRINK-geld", "das, was man zusätzlich gibt")],
      ["Kann ich mit Karte zahlen?", "Zusammen oder getrennt?", "Stimmt so.",
       "Können wir eine Ratenzahlung vereinbaren?"],
      "„Zusammen oder getrennt?“ fragt die Bedienung fast immer. Getrennt zahlen ist völlig normal und niemandem peinlich."),

    A("gesundheit", "Arzt, Apotheke, Notruf",
      "Wer krank ist, geht zuerst zum Hausarzt. Der schickt weiter.",
      ["Hausarzt zuerst. Zu einem Facharzt braucht man oft eine Überweisung — und Geduld, Termine dauern.",
       "Versichertenkarte immer mitnehmen. Ohne sie muss man später zahlen oder nachreichen.",
       "Apotheken verkaufen auch Medikamente ohne Rezept und beraten kostenlos. Nachts und sonntags hat immer eine in der Nähe Notdienst — welche, steht online und an jeder Apothekentür.",
       "112 ist der Notruf für Rettungsdienst und Feuerwehr, 110 für die Polizei. Beide kostenlos, von jedem Telefon.",
       "116117 ist der ärztliche Bereitschaftsdienst — für alles, was nicht lebensbedrohlich ist, aber nicht bis Montag warten kann.",
       "Beim Notruf sagt man: wo, was passiert ist, wie viele Verletzte, und wartet auf Rückfragen."],
      [w("der Hausarzt", "HAUS-arzt", "der Arzt, zu dem man zuerst geht"),
       w("die Überweisung", "Ü-ber-WEI-sung", "der Zettel zum Facharzt"),
       w("das Rezept", "Re-ZEPT", "der Zettel für ein Medikament"),
       w("der Notdienst", "NOT-dienst", "wer nachts und sonntags geöffnet hat"),
       w("die Versichertenkarte", "Ver-SI-cher-ten-kar-te", "die Karte der Krankenkasse")],
      ["Ich brauche einen Termin, bitte.", "Haben Sie etwas gegen Halsschmerzen?",
       "Ich hätte gern eine Überweisung zum Hautarzt."],
      "112 auswendig können. Man muss dabei nicht perfekt Deutsch sprechen — Adresse und „Notfall“ reichen, der Rest wird gefragt."),

    A("schule", "Schule und Kita",
      "Schulpflicht ab sechs Jahren. Und die Eltern werden mehr eingebunden, als viele erwarten.",
      ["Es gibt Schulpflicht, keine reine Bildungspflicht: Zu Hause unterrichten ist nicht erlaubt.",
       "Elternabende und Elternsprechtage sind wichtig. Auch wenn alles gut läuft, geht man hin.",
       "Entschuldigungen bei Krankheit müssen schriftlich kommen — am selben Morgen anrufen und am nächsten Tag den Zettel mitgeben.",
       "Kita-Platz früh anmelden, oft schon in der Schwangerschaft. Ab dem ersten Geburtstag besteht ein Rechtsanspruch.",
       "Es gibt Geld: Kindergeld für jedes Kind, dazu je nach Einkommen Wohngeld, Bildungs- und Teilhabepaket (für Schulranzen, Ausflüge, Musikschule).",
       "Nach der vierten Klasse entscheidet sich die weiterführende Schule. Diese Entscheidung ist nicht endgültig — der Wechsel ist später möglich."],
      [w("die Schulpflicht", "SCHUL-pflicht", "dass jedes Kind zur Schule gehen muss"),
       w("der Elternabend", "EL-tern-a-bend", "das Treffen der Eltern mit der Lehrerin"),
       w("das Kindergeld", "KIN-der-geld", "das Geld vom Staat für jedes Kind"),
       w("der Rechtsanspruch", "RECHTS-an-spruch", "wenn man ein Recht auf etwas hat"),
       w("die Klassenfahrt", "KLAS-sen-fahrt", "die mehrtägige Reise mit der Klasse")],
      ["Mein Sohn ist heute krank.", "Wann ist der nächste Elternabend?",
       "Gibt es Unterstützung für die Klassenfahrt?"],
      "Beim Bildungs- und Teilhabepaket fragen viele nicht nach, weil sie nicht davon wissen. Es deckt Ranzen, Ausflüge, Nachhilfe und Vereinsbeiträge."),

    A("vereine", "Vereine — der schnellste Weg zu Leuten",
      "Es gibt in Deutschland über 600.000 Vereine. Sie sind der einfachste Weg, Kontakte zu knüpfen.",
      ["Sportverein, Chor, Feuerwehr, Schachclub, Kleingarten, Musikschule — für fast alles gibt es einen Verein.",
       "Der Beitrag ist meistens klein, oft unter zehn Euro im Monat. Für Kinder gibt es Ermäßigungen.",
       "Man darf erst einmal zum Schnuppern kommen, ohne einzutreten.",
       "Ein Verein ist kein Kurs: Man gehört dazu, macht mit, hilft beim Sommerfest. Genau daraus entstehen Freundschaften.",
       "Ehrenamt: Wer sich engagiert, lernt am schnellsten Deutsch — und lernt Leute kennen, die ihn kennenlernen wollen."],
      [w("der Verein", "Ver-EIN", "eine Gruppe mit gemeinsamem Interesse"),
       w("der Beitrag", "BEI-trag", "was man im Monat zahlt"),
       w("schnuppern", "SCHNUP-pern", "einmal ausprobieren"),
       w("das Ehrenamt", "EH-ren-amt", "freiwillige Arbeit ohne Bezahlung")],
      ["Kann ich einmal zum Schnuppertraining kommen?", "Was kostet der Beitrag im Monat?",
       "Ich würde gern mithelfen."],
      "Wer nach einem Jahr in Deutschland noch keine deutschen Freunde hat, liegt das fast nie an der Sprache — sondern daran, dass man sich nirgends regelmäßig trifft."),

    A("aemter", "Behörden verstehen",
      "Welches Amt macht was? Das ist am Anfang das größte Rätsel.",
      ["Bürgeramt / Einwohnermeldeamt: Anmeldung, Ausweis, Führungszeugnis.",
       "Ausländerbehörde: Aufenthaltstitel, Verlängerungen.",
       "Agentur für Arbeit: Arbeitsuche, Arbeitslosengeld I, Weiterbildung.",
       "Jobcenter: Bürgergeld, Miete, Bildung und Teilhabe.",
       "Familienkasse: Kindergeld.",
       "Finanzamt: Steuern und Steuernummer.",
       "Jugendamt: Kita-Platz, Unterstützung für Familien. Es hilft — es nimmt nicht einfach Kinder weg, das ist ein hartnäckiges Gerücht.",
       "Zu jedem Termin: Ausweis, alle Briefe zum Thema und einen Zettel mit den eigenen Fragen."],
      [w("die Behörde", "Be-HÖR-de", "das Amt"),
       w("der Antrag", "AN-trag", "das Formular, mit dem man etwas beantragt"),
       w("die Bescheinigung", "Be-SCHEI-ni-gung", "der Nachweis über etwas"),
       w("der Aufenthaltstitel", "AUF-ent-halts-ti-tel", "die Erlaubnis, hier zu leben"),
       w("die Unterlagen", "UN-ter-la-gen", "alle Papiere zusammen")],
      ["Welche Unterlagen brauche ich dafür?", "Könnten Sie mir das bitte aufschreiben?",
       "An wen muss ich mich damit wenden?"],
      "„Könnten Sie mir das bitte aufschreiben?“ ist der nützlichste Satz auf jedem Amt."),

    A("essen", "Essen und Einladungen",
      "Wer eingeladen wird, bringt etwas mit — und fragt vorher.",
      ["Zum Essen eingeladen: Blumen, Wein oder etwas Süßes mitbringen. Nichts Teures.",
       "Vorher sagen, wenn man etwas nicht isst. Das ist nicht unhöflich, sondern hilfreich: „Ich esse kein Schweinefleisch“ reicht völlig.",
       "„Guten Appetit“ sagt man, bevor alle anfangen. Man wartet, bis alle am Tisch sind.",
       "Schuhe ausziehen: In vielen Haushalten üblich. Am Eingang schauen, ob dort Schuhe stehen.",
       "Beim Bezahlen im Restaurant zahlt jeder selbst, wenn nichts anderes gesagt wurde. Wer einlädt, sagt das ausdrücklich.",
       "Abendessen ist oft früh — zwischen 18 und 19 Uhr. Und häufig kalt: Brot, Käse, Wurst. Das heißt „Abendbrot“."],
      [w("die Einladung", "EIN-la-dung", "wenn jemand einen zu sich bittet"),
       w("das Abendbrot", "A-bend-brot", "das kalte Abendessen"),
       w("mitbringen", "MIT-brin-gen", "etwas zum Besuch mitnehmen"),
       w("vegetarisch", "ve-ge-TA-risch", "ohne Fleisch"),
       w("halal", "ha-LAL", "nach islamischen Regeln erlaubt")],
      ["Kann ich etwas mitbringen?", "Ich esse kein Schweinefleisch — passt das?",
       "Guten Appetit!", "Das hat sehr gut geschmeckt, danke!"],
      "Fragen, ob man etwas mitbringen soll, ist immer richtig. Die Antwort ist fast immer „nichts“ — man bringt trotzdem eine Kleinigkeit."),

    A("zutaten", "Einkaufen: die Zutatenliste lesen",
      "Was drin ist, steht auf jeder Packung — hinten, klein, aber vollständig. Wer weiß, worauf er schauen muss, findet es in fünf Sekunden.",
      ["Die Zutaten stehen IMMER nach Menge sortiert: Was zuerst steht, ist am meisten drin.",
       "Gelatine (auch „Speisegelatine\u201c oder E 441) steckt in vielen Gummisüßigkeiten, Marshmallows, manchen Joghurts und Puddings. Sie kommt vom Tier.",
       "Wer Gelatine meiden will, hat es leicht: Steht „vegan\u201c auf der Packung, ist garantiert keine drin. Das Wort ist geschützt und zuverlässig.",
       "Alkohol taucht als „Alkohol\u201c, „Ethanol\u201c, „Rum-Aroma\u201c oder „Weinbrand\u201c auf — vor allem in Pralinen, Weihnachtsgebäck und manchen Soßen.",
       "Schweinefleisch steht als „Schweinefleisch\u201c oder „Schweineschmalz\u201c in der Liste. „Speisefett\u201c allein sagt nichts, dann steht die Herkunft daneben.",
       "Halal-Siegel gibt es in vielen Supermärkten, meist an der Kühltheke und im Regal mit internationalen Produkten. Es ist ein freiwilliges Siegel — kein Siegel heißt nicht automatisch, dass etwas nicht erlaubt wäre.",
       "Ohne Gelatine und ohne Alkohol kommen ganz normale Supermarktwaren aus, die es überall gibt: Nüsse, Mandeln, Cashewkerne, Sonnenblumenkerne, Studentenfutter, Trockenfrüchte und Datteln; Chips, Salzstangen, Erdnussflips, Popcorn, Reis- und Maiswaffeln, Knäckebrot; Müsliriegel, Sesamriegel und Fruchtriegel; dazu Hummus, Oliven, Fladenbrot und Ayran.",
       "Aus der Türkei, aus dem arabischen Raum und vom Balkan: Baklava, Halva, Lokum, Simit und Börek — in jedem türkischen Supermarkt und inzwischen in vielen normalen."],
      [w("die Zutatenliste", "ZU-ta-ten-lis-te", "was alles drin ist"),
       w("die Gelatine", "Ge-la-TI-ne", "ein Bindemittel vom Tier"),
       w("vegan", "ve-GAN", "ganz ohne tierische Zutaten"),
       w("halal", "ha-LAL", "nach islamischen Regeln erlaubt"),
       w("koscher", "KO-scher", "nach jüdischen Regeln erlaubt"),
       w("das Siegel", "SIE-gel", "das Zeichen auf der Packung"),
       w("das Knabberzeug", "KNAB-ber-zeug", "Chips, Nüsse, Salzstangen")],
      ["Ist da Gelatine drin?", "Haben Sie etwas ohne Schweinefleisch?",
       "Wo finde ich die Halal-Produkte?", "Ist das vegan?"],
      "„Vegan\u201c ist die einfachste Abkürzung: kein Fleisch, keine Gelatine, kein Schmalz. Wer nur Gelatine meiden will, findet damit in jedem Supermarkt sofort etwas."),
    A("sprache", "Deutsch lernen im Alltag",
      "Der Kurs ist die eine Hälfte. Die andere passiert draußen.",
      ["Integrationskurs: 600 Stunden Sprache plus 100 Stunden Orientierungskurs, danach die Prüfung „Leben in Deutschland“.",
       "Sprachniveaus: A1 und A2 für den Alltag, B1 für die Einbürgerung, B2 und C1 für viele Berufe.",
       "Die Volkshochschule (VHS) ist überall und günstig. Viele Städte haben Sprachcafés, wo man einfach reden kann — kostenlos.",
       "Sagen, dass man noch lernt, hilft: „Ich lerne noch Deutsch, könnten Sie bitte langsamer sprechen?“ Fast alle machen es dann.",
       "Fernsehen mit deutschen Untertiteln, nicht mit Untertiteln in der Muttersprache.",
       "Fehler machen ist der Weg, nicht das Hindernis. Wer schweigt, um keinen Fehler zu machen, lernt am langsamsten."],
      [w("der Integrationskurs", "In-te-gra-TI-ons-kurs", "Sprach- und Orientierungskurs zusammen"),
       w("die Volkshochschule", "VOLKS-hoch-schu-le", "die günstige Abendschule für alle"),
       w("das Sprachniveau", "SPRACH-ni-veau", "A1 bis C2"),
       w("die Einbürgerung", "EIN-bür-ge-rung", "wenn man deutscher Staatsbürger wird")],
      ["Ich lerne noch Deutsch — könnten Sie bitte langsamer sprechen?",
       "Wie sagt man das auf Deutsch?", "Was bedeutet dieses Wort?"],
      "„Wie sagt man das auf Deutsch?“ — mit diesem einen Satz lernt man mehr Wörter als mit jeder Vokabelliste."),
  ];

  const ALLTAG_IT = [
    A("orari", "Zeiten und Rhythmus",
      "Der Tag ist anders getaktet als in Deutschland.",
      ["Viele Geschäfte machen mittags zu („la pausa pranzo“), oft von 13 bis 16 Uhr.",
       "Abendessen ist spät: ab 20 Uhr, in Süditalien auch später.",
       "Ein Cappuccino nach 11 Uhr gilt als seltsam — nach dem Essen trinkt man Espresso.",
       "Im August ist das halbe Land im Urlaub („chiuso per ferie“)."],
      [w("la pausa pranzo", "PRAN-zo", "die Mittagspause"),
       w("l'aperitivo", "a-pe-ri-TI-vo", "das Getränk mit Kleinigkeiten vor dem Abendessen"),
       w("chiuso", "CHIU-so", "geschlossen")],
      ["A che ora aprite?", "Siete aperti a pranzo?"],
      "Der „aperitivo“ um 19 Uhr ist ein eigener sozialer Termin — dazu wird man eingeladen."),

    A("bar", "In der Bar",
      "Die „bar“ ist kein Nachtlokal, sondern das Café an der Ecke.",
      ["Man trinkt den Espresso im Stehen an der Theke — das ist billiger als am Tisch.",
       "In vielen Bars zahlt man zuerst an der Kasse und zeigt dem Barista den Bon.",
       "„Un caffè“ heißt immer Espresso. Wer etwas anderes will, sagt es dazu."],
      [w("il bancone", "ban-CO-ne", "die Theke"),
       w("lo scontrino", "scon-TRI-no", "der Kassenbon"),
       w("il caffè macchiato", "mac-CHIA-to", "Espresso mit einem Tropfen Milch")],
      ["Un caffè al banco, per favore.", "Pago prima alla cassa?"],
      "Am Tisch zu sitzen kostet oft das Doppelte — das ist kein Betrug, sondern ausgeschildert."),

    A("gesti", "Die Hände",
      "Italienisch spricht man mit den Händen mit. Das ist keine Show, sondern Teil der Sprache.",
      ["Fingerspitzen zusammen, Hand auf und ab: „Was willst du denn?“ / „Was soll das?“",
       "Handrücken unter dem Kinn nach vorn: „Ist mir egal.“",
       "Zeigefinger an die Wange drehen: „Das ist lecker.“",
       "Wer die Gesten nicht benutzt, wird trotzdem verstanden — wer sie kennt, versteht mehr."],
      [w("il gesto", "GE-sto", "die Geste"),
       w("la mano", "MA-no", "die Hand")],
      ["Ma che vuoi?", "Buonissimo!"],
      ""),

    A("saluti", "Grüßen",
      "Wann „ciao“, wann „buongiorno“ — das ist die häufigste Unsicherheit.",
      ["„Ciao“ nur bei Menschen, die man duzt. Zu Fremden, im Laden, im Amt: „buongiorno“ oder „buonasera“.",
       "„Buonasera“ gilt ab dem späten Nachmittag — in Süditalien früher als im Norden.",
       "„Salve“ ist die neutrale Zwischenform: weder zu förmlich noch zu vertraut.",
       "Beim Betreten eines kleinen Ladens grüßt man — wie in Deutschland."],
      [w("salve", "SAL-ve", "neutraler Gruß"),
       w("arrivederci", "ar-ri-ve-DER-ci", "auf Wiedersehen")],
      ["Buongiorno!", "Salve!", "Arrivederci, buona giornata!"],
      "„Salve“ rettet jede Situation, in der man nicht weiß, ob geduzt oder gesiezt wird."),
  ];


  /* =========================================================
     WEGWEISER — die ersten Wochen in Deutschland
     ---------------------------------------------------------
     GEWÜNSCHT: „Wegweiser: Orientierung auf der Seite und in
     Deutschland."

     Der zweite Teil. In der richtigen Reihenfolge, denn vieles
     hängt voneinander ab: ohne Anmeldung keine Meldebescheinigung,
     ohne die kein Konto, ohne Konto kein Gehalt.
     ========================================================= */
  const W = (id, titel, wann, wo, brauchst, schritte, saetze, hinweis) =>
    ({ id, titel, wann, wo, brauchst, schritte, saetze, hinweis });

  const WEGWEISER_DE = [
    W("anmeldung", "1. Wohnung anmelden", "innerhalb von zwei Wochen nach dem Einzug",
      "Bürgeramt / Einwohnermeldeamt deiner Stadt",
      ["Ausweis oder Pass", "Wohnungsgeberbestätigung (bekommst du vom Vermieter)", "wenn du nicht allein kommst: die Papiere aller Personen"],
      ["Termin online buchen — ohne Termin wartet man oft stundenlang oder wird weggeschickt.",
       "Zum Termin alle Papiere mitnehmen, auch die der Kinder.",
       "Du bekommst sofort die Meldebescheinigung. Heb sie gut auf — du brauchst sie überall."],
      ["Guten Tag, ich möchte mich anmelden. Ich bin letzte Woche umgezogen.",
       "Ich habe einen Termin um zehn Uhr.", "Könnten Sie mir das bitte aufschreiben?"],
      "Das ist der erste Schritt, und alles andere hängt daran. Ohne Anmeldung gibt es kein Konto, keine Steuernummer und kein Kindergeld."),

    W("steuernummer", "2. Steuer-Identifikationsnummer", "kommt von selbst, zwei bis drei Wochen nach der Anmeldung",
      "kommt mit der Post — du musst nichts tun",
      ["nur deinen Briefkasten"],
      ["Nach der Anmeldung schickt das Bundeszentralamt für Steuern die Nummer automatisch zu.",
       "Die Nummer ist lebenslang gleich und ändert sich auch beim Umzug nicht.",
       "Dein Arbeitgeber braucht sie, sonst zahlst du zu viel Steuern."],
      ["Ich warte noch auf meine Steuer-Identifikationsnummer.",
       "Können Sie mir die Nummer noch einmal schicken?"],
      "Den Brief nicht wegwerfen. Wenn er verloren geht, kann man ihn online neu anfordern — das dauert aber wieder Wochen."),

    W("konto", "3. Bankkonto eröffnen", "sobald die Meldebescheinigung da ist",
      "eine Bank oder Sparkasse — oder online",
      ["Ausweis oder Pass", "Meldebescheinigung", "manchmal: Nachweis über Arbeit oder Studium"],
      ["Ein Girokonto reicht. Bei vielen Banken kostet es vier bis sechs Euro im Monat.",
       "Für Auszubildende und Studierende ist es fast überall kostenlos — danach fragen.",
       "Du bekommst eine EC-Karte (Girocard). Die PIN kommt in einem eigenen Brief."],
      ["Guten Tag. Ich möchte ein Girokonto eröffnen.",
       "Gibt es auch ein Konto ohne Grundgebühr?", "Wann bekomme ich die Karte?"],
      "Ohne Konto gibt es weder Gehalt noch Miete noch Kindergeld. Deshalb gleich nach der Anmeldung erledigen."),

    W("krankenkasse", "4. Krankenversicherung", "so früh wie möglich — sie ist Pflicht",
      "eine gesetzliche Krankenkasse (AOK, TK, Barmer, DAK und andere)",
      ["Ausweis", "Meldebescheinigung", "Steuer-Identifikationsnummer", "Arbeitsvertrag, wenn du arbeitest"],
      ["Wer angestellt ist, wird über den Arbeitgeber angemeldet — die Kasse darfst du selbst wählen.",
       "Die Kassen unterscheiden sich kaum im Leistungsumfang, aber ein wenig im Beitrag.",
       "Du bekommst die Versichertenkarte per Post. Sie musst du zu jedem Arztbesuch mitnehmen."],
      ["Ich möchte mich bei Ihnen versichern.",
       "Welche Unterlagen brauchen Sie von mir?", "Wann bekomme ich meine Karte?"],
      "In Deutschland ist die Krankenversicherung für alle Pflicht. Ohne sie zahlt man jeden Arztbesuch selbst."),

    W("auslaenderbehoerde", "5. Ausländerbehörde", "je nach Papieren — der Termin steht meist schon fest",
      "die Ausländerbehörde deiner Stadt",
      ["Pass", "Meldebescheinigung", "biometrisches Passfoto", "alle Briefe zum Thema"],
      ["Termin frühzeitig buchen — die Wartezeiten sind lang.",
       "Immer ALLE Briefe mitnehmen, auch die, die du nicht verstehst.",
       "Wenn du etwas nicht verstehst: nachfragen und dir alles aufschreiben lassen."],
      ["Ich habe einen Termin wegen meines Aufenthaltstitels.",
       "Entschuldigung, das habe ich nicht verstanden. Könnten Sie das bitte wiederholen?",
       "Welche Unterlagen brauche ich beim nächsten Mal?"],
      "Fristen ernst nehmen: Ein Aufenthaltstitel muss VOR dem Ablaufdatum verlängert werden, nicht danach."),

    W("sprachkurs", "6. Sprachkurs anmelden", "so früh wie möglich",
      "BAMF (Integrationskurs) oder die Volkshochschule",
      ["Ausweis", "je nach Fall: Berechtigungsschein vom BAMF oder vom Jobcenter"],
      ["Der Integrationskurs besteht aus 600 Stunden Sprache und 100 Stunden Orientierungskurs.",
       "Am Ende stehen die Prüfung „Deutsch-Test für Zuwanderer\u201c und „Leben in Deutschland\u201c.",
       "Mit B1 kann man später die Einbürgerung beantragen.",
       "Die Volkshochschule hat daneben günstige Abendkurse für alle Niveaus."],
      ["Ich möchte mich für einen Deutschkurs anmelden.",
       "Auf welchem Niveau soll ich anfangen?", "Wann beginnt der nächste Kurs?"],
      "Neben dem Kurs helfen Sprachcafés am meisten — dort redet man einfach, kostenlos und ohne Prüfung."),

    W("arbeit", "7. Arbeit und Anerkennung", "sobald du darfst",
      "Agentur für Arbeit, Jobcenter, und für Abschlüsse: anerkennung-in-deutschland.de",
      ["Lebenslauf", "Zeugnisse (übersetzt und beglaubigt)", "Aufenthaltstitel mit Arbeitserlaubnis"],
      ["Lass deinen Abschluss anerkennen. In vielen Berufen darf man ohne Anerkennung nicht arbeiten — in anderen bringt sie deutlich mehr Gehalt.",
       "Die Agentur für Arbeit berät kostenlos, auch wenn du noch keinen Anspruch auf Geld hast.",
       "Ein deutscher Lebenslauf ist knapp, tabellarisch und ohne lange Sätze. Ein Foto ist üblich, aber nicht Pflicht."],
      ["Ich möchte meinen Abschluss anerkennen lassen.",
       "Ich suche Arbeit als Elektriker. Können Sie mich beraten?",
       "Welche Unterlagen brauche ich für die Bewerbung?"],
      "Ehrenamt und Praktikum zählen in Deutschland viel — sie sind oft der schnellste Weg in einen festen Job."),

    W("kinder", "8. Kita und Schule", "so früh wie möglich, oft mit langer Wartezeit",
      "Jugendamt (Kita) und das Schulamt oder direkt die Schule",
      ["Geburtsurkunde des Kindes", "Meldebescheinigung", "Impfpass (Masernimpfung ist Pflicht)"],
      ["Ab dem ersten Geburtstag hat jedes Kind ein Recht auf einen Kita-Platz — anmelden muss man sich trotzdem selbst, und früh.",
       "Schulpflicht besteht ab sechs Jahren. Die Schule wird meist nach Wohnort zugeteilt.",
       "Neu zugewanderte Kinder kommen oft zuerst in eine Willkommens- oder Vorbereitungsklasse."],
      ["Ich möchte mein Kind für die Kita anmelden.",
       "Mein Sohn ist sechs. Wo melde ich ihn für die Schule an?",
       "Gibt es Unterstützung für Schulmaterial?"],
      "Beim Jugendamt nachfragen, ob es eine zentrale Kita-Anmeldung gibt — dann reicht eine Anmeldung für viele Einrichtungen."),

    W("kindergeld", "9. Kindergeld beantragen", "sobald Konto und Steuernummer da sind",
      "Familienkasse (gehört zur Agentur für Arbeit)",
      ["Geburtsurkunde des Kindes", "Steuer-Identifikationsnummer von dir und vom Kind", "Kontodaten", "Aufenthaltstitel"],
      ["Der Antrag geht online oder auf Papier.",
       "Kindergeld wird rückwirkend nur für sechs Monate gezahlt — je früher, desto besser.",
       "Je nach Einkommen kommen Kinderzuschlag und das Bildungs- und Teilhabepaket dazu (Schulranzen, Ausflüge, Nachhilfe, Vereinsbeitrag)."],
      ["Ich möchte Kindergeld beantragen.",
       "Welche Unterlagen fehlen noch?", "Ab wann wird gezahlt?"],
      "Nach dem Bildungs- und Teilhabepaket fragen viele nicht, weil sie nicht davon wissen. Es deckt erstaunlich viel ab."),

    W("hausarzt", "10. Hausarzt suchen", "bevor du krank wirst",
      "eine Hausarztpraxis in deiner Nähe",
      ["Versichertenkarte"],
      ["Ruf an und frag, ob die Praxis noch neue Patienten aufnimmt — viele sind voll.",
       "Der Hausarzt ist die erste Stelle für alles. Er überweist zum Facharzt.",
       "116117 ist der ärztliche Bereitschaftsdienst für abends und am Wochenende, 112 der Notruf."],
      ["Guten Tag, nehmen Sie noch neue Patienten auf?",
       "Ich hätte gern einen Termin für eine Erstuntersuchung.",
       "Ich brauche eine Überweisung."],
      "Such dir den Hausarzt in ruhigen Zeiten, nicht wenn du schon Fieber hast. Dann ist es viel schwerer."),

    W("vertraege", "11. Handy, Internet, Rundfunkbeitrag", "in den ersten Wochen",
      "Läden in der Stadt, online — und rundfunkbeitrag.de",
      ["Ausweis", "Kontodaten", "Meldebescheinigung"],
      ["Achte auf die Laufzeit: 24 Monate sind üblich, die Kündigungsfrist meist drei Monate.",
       "Prepaid ohne Vertrag ist teurer pro Monat, aber man kommt jederzeit wieder heraus.",
       "Der Rundfunkbeitrag ist Pflicht — pro Wohnung, nicht pro Person, auch ohne Fernseher. Anmelden muss man sich selbst, sonst kommt später eine Nachzahlung.",
       "Eine private Haftpflichtversicherung ist keine Pflicht, kostet aber wenig und wird in Deutschland fast überall erwartet."],
      ["Wie lange läuft der Vertrag?", "Wie hoch ist die Kündigungsfrist?",
       "Ich möchte meine Wohnung für den Rundfunkbeitrag anmelden."],
      "Verträge in Deutschland verlängern sich nicht mehr automatisch um ein Jahr — seit 2022 kann man nach Ablauf monatlich kündigen."),

    W("fuehrerschein", "12. Führerschein umschreiben", "je nach Herkunftsland innerhalb von sechs Monaten",
      "Führerscheinstelle deiner Stadt",
      ["Führerschein aus dem Herkunftsland", "beglaubigte Übersetzung", "Passfoto", "Sehtest", "Erste-Hilfe-Kurs"],
      ["Aus manchen Ländern wird der Führerschein einfach umgeschrieben, aus anderen muss man Prüfungen nachholen.",
       "Die Frist beginnt mit der Anmeldung. Danach darf man mit dem alten Führerschein nicht mehr fahren.",
       "Welche Regel für dein Land gilt, sagt dir die Führerscheinstelle."],
      ["Ich möchte meinen Führerschein umschreiben lassen.",
       "Welche Prüfungen muss ich nachholen?", "Bis wann muss das erledigt sein?"],
      "Diese Frist wird sehr oft übersehen. Wer sie verpasst, fährt ohne gültige Fahrerlaubnis — und das ist eine Straftat."),

    W("ankommen", "13. Ankommen — der Teil, den niemand aufschreibt", "ab dem ersten Tag",
      "Verein, Nachbarschaft, Sprachcafé, Ehrenamt",
      ["nichts außer Zeit"],
      ["Tritt einem Verein bei. Sport, Chor, Schach, Feuerwehr, Kleingarten — der Beitrag ist klein, und man darf erst einmal schnuppern.",
       "Grüß im Treppenhaus. Es kostet nichts und verändert viel.",
       "Sag den Leuten, dass du noch lernst. Fast alle sprechen dann langsamer und freuen sich, dass du redest.",
       "Such dir ein Ehrenamt. Wer regelmäßig mit denselben Menschen etwas tut, lernt die Sprache schneller als in jedem Kurs."],
      ["Kann ich einmal zum Schnuppertraining kommen?",
       "Ich lerne noch Deutsch — könnten Sie bitte langsamer sprechen?",
       "Ich würde gern mithelfen."],
      "Wer nach einem Jahr noch keine deutschen Bekannten hat, dem fehlt fast nie die Sprache — es fehlt der Ort, an dem man sich regelmäßig trifft."),
  ];

  /* =========================================================
     FRAGEN ZUM ÜBEN
     ========================================================= */
  const QUIZ_DE = [
    { frage: "An welchem Tag gibt es in Deutschland die Weihnachtsgeschenke?", richtig: "Am Abend des 24. Dezember", falsch: ["Am Morgen des 25. Dezember", "Am 6. Januar", "Am 26. Dezember"], erkl: "Heiligabend, abends — anders als in vielen anderen Ländern. Der 25. und 26. sind die ruhigen Familientage." },
    { frage: "Wann darf man jemandem zum Geburtstag gratulieren?", richtig: "Frühestens am Tag selbst", falsch: ["Am Tag davor ist am höflichsten", "Eine Woche vorher", "Wann man will"], erkl: "Vorher zu gratulieren gilt als Unglück. Lieber einen Tag zu spät." },
    { frage: "Was kommt in die gelbe Tonne?", richtig: "Verpackungen aus Plastik, Metall und Verbund", falsch: ["Essensreste", "Papier und Pappe", "Altglas"], erkl: "Gelb = Verpackung. Blau = Papier, braun = Bio, grau = Restmüll, Glas zum Container." },
    { frage: "Ab wann gilt in einem normalen Mietshaus die Nachtruhe?", richtig: "Ab 22 Uhr", falsch: ["Ab 20 Uhr", "Ab 23 Uhr", "Ab Mitternacht"], erkl: "22 bis 6 Uhr. Sonntags gilt sie den ganzen Tag." },
    { frage: "Wie viel Pfand ist auf einer Einweg-Plastikflasche?", richtig: "25 Cent", falsch: ["8 Cent", "50 Cent", "Gar keins"], erkl: "Einweg 25 Cent, Mehrweg-Glas 8 oder 15 Cent, Bierkasten bis 3,10 Euro." },
    { frage: "Welche Nummer wählt man bei einem medizinischen Notfall?", richtig: "112", falsch: ["110", "116117", "115"], erkl: "112 für Rettungsdienst und Feuerwehr, 110 für die Polizei, 116117 für den ärztlichen Bereitschaftsdienst." },
    { frage: "Woran erinnert der 3. Oktober?", richtig: "An die Wiedervereinigung 1990", falsch: ["An den Mauerfall 1989", "An das Ende des Zweiten Weltkriegs", "An die Gründung der Bundesrepublik"], erkl: "Der Mauerfall war am 9. November 1989 — der 3. Oktober 1990 ist der Tag der Wiedervereinigung." },
    { frage: "Was macht man an Sankt Martin?", richtig: "Kinder ziehen mit Laternen durch die Straßen", falsch: ["Man verkleidet sich", "Man stellt Stiefel vor die Tür", "Man zündet ein Osterfeuer an"], erkl: "Laternenumzug am 11. November, danach Martinsfeuer und Weckmann." },
    { frage: "Wie lange hat man nach einem Umzug Zeit, sich anzumelden?", richtig: "Zwei Wochen", falsch: ["Drei Monate", "Sechs Wochen", "Es gibt keine Frist"], erkl: "Zwei Wochen beim Bürgeramt. Ohne Anmeldung gibt es kein Konto und keine Meldebescheinigung." },
    { frage: "Was sagt man am 30. Dezember zu jemandem?", richtig: "Guten Rutsch!", falsch: ["Frohes neues Jahr!", "Prost Neujahr!", "Alles Gute zum neuen Jahr, es hat schon begonnen"], erkl: "„Guten Rutsch“ vorher, „frohes neues Jahr“ ab dem 1. Januar." },
    { frage: "Wer bringt am Geburtstag im Büro den Kuchen mit?", richtig: "Das Geburtstagskind selbst", falsch: ["Die Kolleg:innen", "Die Chefin", "Niemand, das ist unüblich"], erkl: "Wer Geburtstag hat, gibt aus — im Büro wie beim Feiern zu Hause." },
    { frage: "Was ist ein Brückentag?", richtig: "Ein Arbeitstag zwischen Feiertag und Wochenende, den man freinimmt", falsch: ["Ein zusätzlicher gesetzlicher Feiertag", "Der Tag, an dem Brücken gesperrt sind", "Ein halber Arbeitstag"], erkl: "Zum Beispiel der Freitag nach Christi Himmelfahrt. Früh beantragen — alle wollen ihn." },
    { frage: "Was heißt „stoßlüften“?", richtig: "Das Fenster kurz ganz öffnen statt lange zu kippen", falsch: ["Die Heizung aufdrehen und das Fenster kippen", "Nachts das Fenster offen lassen", "Mit einem Ventilator lüften"], erkl: "Dreimal täglich fünf bis zehn Minuten ganz auf. Ein gekipptes Fenster kühlt die Wände aus und macht Schimmel." },
    { frage: "Wann ist Karneval am größten?", richtig: "Im Rheinland, besonders in Köln, Düsseldorf und Mainz", falsch: ["In Hamburg und Bremen", "In Berlin", "Überall gleich"], erkl: "Im Norden merkt man fast nichts davon. In Köln ruft man „Alaaf“, in Mainz und Düsseldorf „Helau“." },
    { frage: "Was gehört NICHT in den Hausmüll?", richtig: "Batterien und alte Medikamente", falsch: ["Benutzte Taschentücher", "Kaputtes Spielzeug aus Plastik", "Zigarettenkippen"], erkl: "Batterien, Elektrogeräte, Farben und Medikamente kommen zum Wertstoffhof oder zurück in den Laden." },
    { frage: "Was antwortet man in Deutschland auf „Wie geht's?“", richtig: "Eine kurze, ehrliche Antwort — und dann zurückfragen", falsch: ["Immer „gut“, egal wie es einem geht", "Gar nichts, es ist nur eine Floskel", "Man erzählt ausführlich"], erkl: "Anders als im Englischen ist es eine echte Frage. „Ganz gut, und dir?“ reicht." },
  ];

  const QUIZ_IT = [
    { frage: "Was bringt die Befana den Kindern?", richtig: "Süßigkeiten — oder Zuckerkohle", falsch: ["Bücher", "Geld", "Blumen"], erkl: "Am 6. Januar. Braven Kindern Süßes, den anderen „carbone“ aus Zucker." },
    { frage: "Was isst man in Italien zu Neujahr?", richtig: "Linsen", falsch: ["Karpfen", "Gans", "Kartoffelsalat"], erkl: "„Le lenticchie“ sollen Geld fürs neue Jahr bringen — dazu cotechino oder zampone." },
    { frage: "Wann bekommt man in Italien die Weihnachtsgeschenke?", richtig: "Am Morgen des 25. Dezember", falsch: ["Am Abend des 24.", "Am 6. Januar", "Am 26. Dezember"], erkl: "Am 24. abends gibt es Fisch, die Geschenke kommen am Morgen des 25." },
    { frage: "Was ist Ferragosto?", richtig: "Der 15. August — fast das ganze Land hat Urlaub", falsch: ["Ein Weinfest im September", "Der italienische Nationalfeiertag", "Ein Fest für Eisenarbeiter"], erkl: "„Chiuso per ferie“ steht dann an sehr vielen Türen." },
    { frage: "Woran erinnert der 2. Juni?", richtig: "An die Entscheidung für die Republik 1946", falsch: ["An die Befreiung 1945", "An die Einigung Italiens 1861", "An das Kriegsende"], erkl: "„Festa della Repubblica“ — mit Parade in Rom. Die Befreiung wird am 25. April gefeiert." },
    { frage: "Wann sagt man „ciao“?", richtig: "Nur bei Menschen, die man duzt", falsch: ["Immer, es ist neutral", "Nur zum Abschied", "Nur bei Fremden"], erkl: "Zu Fremden „buongiorno“, „buonasera“ oder das neutrale „salve“." },
    { frage: "Was ist eine „bar“ in Italien?", richtig: "Das Café an der Ecke", falsch: ["Ein Nachtlokal", "Eine Kneipe mit Bier", "Ein Restaurant"], erkl: "Espresso, Cornetto, Zeitung — morgens um sieben schon voll." },
    { frage: "Warum kostet der Kaffee am Tisch mehr als an der Theke?", richtig: "Weil der Tischservice extra kostet — das ist normal und ausgeschildert", falsch: ["Weil man Touristen erkennt", "Weil der Kaffee anders ist", "Das stimmt nicht"], erkl: "„Al banco“ ist billiger. Wer sitzen will, zahlt den Service mit." },
  ];

  return {
    FESTE: { de: FESTE_DE, it: FESTE_IT },
    ALLTAG: { de: ALLTAG_DE, it: ALLTAG_IT },
    QUIZ: { de: QUIZ_DE, it: QUIZ_IT },
    WEGWEISER: { de: WEGWEISER_DE },
  };
})();
